# Process TOA5 data

## TOA5_2806.ts_data.dat

Split large (~28 mil rows, 3.2 GB) TOA5 file into manageable (max. 1 mil rows, ~110 MB) files

In [20]:
# view the data
system("sed -n '1,7p' 'data/TOA5/TOA5_2806.ts_data.dat'", intern = TRUE)

[1] "\"TOA5\",\"2806\",\"CR1000\",\"2806\",\"CR1000.Std.06\",\"CPU:3D_LI_TGA_VNOTDNEW.CR1\",\"21445\",\"ts_data\"\r"
[2] "\"TIMESTAMP\",\"RECORD\",\"Ux\",\"Uy\",\"Uz\",\"co2\",\"h2o\",\"n2o\",\"Ts\",\"press\",\"diag_csat\",\"t_hmp\",\"e_hmp\"\r"
[3] "\"TS\",\"RN\",\"m/s\",\"m/s\",\"m/s\",\"mg/m^3\",\"g/m^3\",\"umol/mol\",\"C\",\"kPa\",\"unitless\",\"C\",\"kPa\"\r"
[4] "\"\",\"\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\"\r"
[5] "\"2014-12-22 11:47:39.3\",761139393,1.69375,0.68975,0.8642501,760.738,8.81152,\"NAN\",12.08542,99.28229,0,11.51643,1.219314\r"
[6] "\"2014-12-22 11:47:39.4\",761139394,1.551,0.1625,1.36275,760.2671,8.790375,\"NAN\",12.10226,99.24676,0,11.51643,1.220242\r"
[7] "\"2014-12-22 11:47:39.5\",761139395,1.51725,-0.11075,1.74625,760.1978,8.794267,\"NAN\",12.16629,99.24676,0,11.80331,1.2455\r"

In [1]:
# read TOA5 dataset
data <- read.csv("data/TOA5/TOA5_2806.ts_data.dat", skip = 4, header = FALSE)

In [4]:
# extract headers
headers <- read.csv(
  "data/TOA5/TOA5_2806.ts_data.dat", skip = 1, header = FALSE, nrows = 3
)

In [5]:
headers

  V1        V2     V3  V4  V5  V6     V7    V8       V9  V10   V11       V12
1 TIMESTAMP RECORD Ux  Uy  Uz  co2    h2o   n2o      Ts  press diag_csat t_hmp
2 TS        RN     m/s m/s m/s mg/m^3 g/m^3 umol/mol C   kPa   unitless  C
3                  Smp Smp Smp Smp    Smp   Smp      Smp Smp   Smp       Smp
  V13
1 e_hmp
2 kPa
3 Smp

In [44]:
# save headers
write.table(
  headers, "data/CSV/TOA5_2806.ts_data.headers.csv", row.names = FALSE,
  col.names = FALSE, sep = ",", quote = FALSE
)

In [2]:
# assign column names
names(data) <- as.matrix(
  read.csv(
    "data/TOA5/TOA5_2806.ts_data.dat", skip = 1, header = FALSE, nrows = 1
  )
)

In [3]:
head(data)

  TIMESTAMP             RECORD    Ux      Uy         Uz        co2
1 2014-12-22 11:47:39.3 761139393 1.69375  0.6897500 0.8642501 760.7380
2 2014-12-22 11:47:39.4 761139394 1.55100  0.1625000 1.3627500 760.2671
3 2014-12-22 11:47:39.5 761139395 1.51725 -0.1107500 1.7462500 760.1978
4 2014-12-22 11:47:39.6 761139396 1.95925 -0.3437500 0.6390001 760.7865
5 2014-12-22 11:47:39.7 761139397 1.36050 -0.4550000 1.2060000 760.8245
6 2014-12-22 11:47:39.8 761139398 0.57650 -0.9160001 1.2277500 760.9031
  h2o      n2o Ts       press    diag_csat t_hmp    e_hmp
1 8.811520 NAN 12.08542 99.28229 0         11.51643 1.219314
2 8.790375 NAN 12.10226 99.24676 0         11.51643 1.220242
3 8.794267 NAN 12.16629 99.24676 0         11.80331 1.245500
4 8.813287 NAN 12.07193 99.24676 0         11.61206 1.227055
5 8.806199 NAN 12.12418 99.25624 0         11.70769 1.235777
6 8.796409 NAN 12.12582 99.22072 0         11.70769 1.236716

In [7]:
summary(data)

                 TIMESTAMP            RECORD                Ux
 2014-12-22 11:47:39.3:       1   Min.   :761139393   Min.   :-65.53
 2014-12-22 11:47:39.4:       1   1st Qu.:768264807   1st Qu.:  0.50
 2014-12-22 11:47:39.5:       1   Median :775390221   Median :  1.36
 2014-12-22 11:47:39.6:       1   Mean   :775390221   Mean   :  1.79
 2014-12-22 11:47:39.7:       1   3rd Qu.:782515635   3rd Qu.:  2.78
 2014-12-22 11:47:39.8:       1   Max.   :789641049   Max.   : 65.53
 (Other)              :28501651                       NA's   :267862
       Uy               Uz              co2                  h2o
 Min.   :-65.53   Min.   :-49.82   Min.   :-5.849e+18   Min.   : -2.122
 1st Qu.: -1.11   1st Qu.: -0.33   1st Qu.: 8.030e+02   1st Qu.:  5.155
 Median :  0.24   Median :  0.00   Median : 8.490e+02   Median :  6.366
 Mean   :  0.62   Mean   :  0.01   Mean   :-3.364e+11   Mean   :  9.375
 3rd Qu.:  2.56   3rd Qu.:  0.34   3rd Qu.: 1.101e+03   3rd Qu.: 10.736
 Max.   : 65.53   Max.   : 45.43   Max.   : 8.143e+16   Max.   :716.880
 NA's   :267862   NA's   :267862
  n2o                 Ts             press          diag_csat
 NAN:28501657   Min.   :-38.26   Min.   : 94.60   Min.   :    0.0
                1st Qu.:  3.65   1st Qu.: 98.73   1st Qu.:    0.0
                Median :  6.31   Median : 99.35   Median :    0.0
                Mean   :  8.41   Mean   : 99.28   Mean   :  783.6
                3rd Qu.: 11.26   3rd Qu.: 99.96   3rd Qu.:    1.0
                Max.   : 72.63   Max.   :101.63   Max.   :61503.0
                NA's   :267862
     t_hmp            e_hmp
 Min.   :-2.861   Min.   :0.4546
 1st Qu.: 3.310   1st Qu.:0.6803
 Median : 5.651   Median :0.7821
 Mean   : 5.889   Mean   :0.8590
 3rd Qu.: 8.487   3rd Qu.:1.0068
 Max.   :15.325   Max.   :1.6238

In [8]:
nrow(data)

[1] 28501657

In [9]:
# split data into manageable chunks (1 mil rows)
data_split <- split(data, (as.numeric(rownames(data)) - 1) %/% 1000000)

In [10]:
str(data_split)

List of 29
 $ 0 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 1 2 3 4 5 6 7 8 9 10 ...
  ..$ RECORD   : int [1:1000000] 761139393 761139394 761139395 761139396 761139397 761139398 761139399 761139400 761139401 761139402 ...
  ..$ Ux       : num [1:1000000] 1.69 1.55 1.52 1.96 1.36 ...
  ..$ Uy       : num [1:1000000] 0.69 0.163 -0.111 -0.344 -0.455 ...
  ..$ Uz       : num [1:1000000] 0.864 1.363 1.746 0.639 1.206 ...
  ..$ co2      : num [1:1000000] 761 760 760 761 761 ...
  ..$ h2o      : num [1:1000000] 8.81 8.79 8.79 8.81 8.81 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 12.1 12.1 12.2 12.1 12.1 ...
  ..$ press    : num [1:1000000] 99.3 99.2 99.2 99.2 99.3 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 11.5 11.5 11.8 11.6 11.7 ...
  ..$ e_hmp    : num [1:1000000] 1.22 1.22 1.25 1.23 1.24 ...
 $ 1 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 1000001 1000002 1000003 1000004 1000005 1000006 1000007 1000008 1000009 1000010 ...
  ..$ RECORD   : int [1:1000000] 762139393 762139394 762139395 762139396 762139397 762139398 762139399 762139400 762139401 762139402 ...
  ..$ Ux       : num [1:1000000] 6.05 4.82 5.35 1.82 5.57 ...
  ..$ Uy       : num [1:1000000] 4.86 4.73 2.92 3.1 4.53 ...
  ..$ Uz       : num [1:1000000] -1.141 -0.271 -0.246 -0.283 -0.752 ...
  ..$ co2      : num [1:1000000] 1409 1447 1406 1383 1388 ...
  ..$ h2o      : num [1:1000000] 29 30 29 28 28.3 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 20.6 20.8 21.8 23.7 21.2 ...
  ..$ press    : num [1:1000000] 98.5 98.5 98.5 98.5 98.5 ...
  ..$ diag_csat: int [1:1000000] 3 3 3 3 3 3 3 3 3 3 ...
  ..$ t_hmp    : num [1:1000000] 11.3 11.3 11.3 11.3 11.3 ...
  ..$ e_hmp    : num [1:1000000] 1.32 1.32 1.32 1.32 1.32 ...
 $ 2 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 2000001 2000002 2000003 2000004 2000005 2000006 2000007 2000008 2000009 2000010 ...
  ..$ RECORD   : int [1:1000000] 763139393 763139394 763139395 763139396 763139397 763139398 763139399 763139400 763139401 763139402 ...
  ..$ Ux       : num [1:1000000] 1.73 1.49 1.44 1.7 1.4 ...
  ..$ Uy       : num [1:1000000] -0.498 -0.399 -0.511 -1.04 -0.664 ...
  ..$ Uz       : num [1:1000000] 0.5212 0.0217 0.2135 0.2165 0.0232 ...
  ..$ co2      : num [1:1000000] 824 824 824 824 824 ...
  ..$ h2o      : num [1:1000000] 5.34 5.33 5.33 5.33 5.33 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 4.27 4.3 4.32 4.37 4.39 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 4.08 4.08 4.08 3.98 4.08 ...
  ..$ e_hmp    : num [1:1000000] 0.726 0.729 0.727 0.722 0.727 ...
 $ 3 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 3000001 3000002 3000003 3000004 3000005 3000006 3000007 3000008 3000009 3000010 ...
  ..$ RECORD   : int [1:1000000] 764139393 764139394 764139395 764139396 764139397 764139398 764139399 764139400 764139401 764139402 ...
  ..$ Ux       : num [1:1000000] 0.546 0.529 0.558 0.524 0.543 ...
  ..$ Uy       : num [1:1000000] 0.626 0.661 0.689 0.694 0.706 ...
  ..$ Uz       : num [1:1000000] 0.0195 -0.002 -0.0045 -0.01 -0.0177 ...
  ..$ co2      : num [1:1000000] 847 850 849 851 851 ...
  ..$ h2o      : num [1:1000000] 5.06 5.05 5.05 5.04 5.04 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 2.78 2.7 2.66 2.62 2.65 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 3.5 3.6 3.6 3.6 3.5 ...
  ..$ e_hmp    : num [1:1000000] 0.7 0.705 0.705 0.705 0.701 ...
 $ 4 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 4000001 4000002 4000003 4000004 4000005 4000006 4000007 4000008 4000009 4000010 ...
  ..$ RECORD   : int [1:1000000] 765139393 765139394 765139395 765139396 765139397 765139398 765139399 765139400 765139401 765139402 ...
  ..$ Ux       : num [1:1000000] 1.248 1.619 1.454 1.32 0.639 ...
  ..$ Uy       : num [1:1000000] -1.86 -1.59 -1.8 -1.71 -2.94 ...
  ..$ Uz       : num [1:1000000] -0.726 -0.659 -0.388 0.25 0.236 ...
  ..$ co2      : num [1:1000000] 1151 1151 1150 1148 1147 ...
  ..$ h2o      : num [1:1000000] 12.3 12.3 12.2 12.1 12.1 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 5.35 5.34 5.33 5.3 5.31 ...
  ..$ press    : num [1:1000000] 99.4 99.4 99.4 99.5 99.5 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 5.39 5.29 5.39 5.29 5.39 ...
  ..$ e_hmp    : num [1:1000000] 0.807 0.802 0.807 0.802 0.806 ...
 $ 5 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 5000001 5000002 5000003 5000004 5000005 5000006 5000007 5000008 5000009 5000010 ...
  ..$ RECORD   : int [1:1000000] 766139393 766139394 766139395 766139396 766139397 766139398 766139399 766139400 766139401 766139402 ...
  ..$ Ux       : num [1:1000000] -0.701 -0.742 -0.529 -0.528 -0.752 ...
  ..$ Uy       : num [1:1000000] 2.38 2.34 2.33 2.28 2.15 ...
  ..$ Uz       : num [1:1000000] 0.396 0.293 0.199 0.159 0.324 ...
  ..$ co2      : num [1:1000000] 878 878 878 878 878 ...
  ..$ h2o      : num [1:1000000] 3.98 3.97 3.97 3.97 3.97 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] -0.486 -0.478 -0.447 -0.489 -0.483 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 0.342 0.534 0.629 0.342 0.438 ...
  ..$ e_hmp    : num [1:1000000] 0.558 0.568 0.571 0.558 0.562 ...
 $ 6 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 6000001 6000002 6000003 6000004 6000005 6000006 6000007 6000008 6000009 6000010 ...
  ..$ RECORD   : int [1:1000000] 767139393 767139394 767139395 767139396 767139397 767139398 767139399 767139400 767139401 767139402 ...
  ..$ Ux       : num [1:1000000] 0.556 0.516 0.525 0.502 0.445 ...
  ..$ Uy       : num [1:1000000] 0.469 0.407 0.522 0.433 0.522 ...
  ..$ Uz       : num [1:1000000] -0.1 -0.1252 -0.0695 -0.1578 -0.105 ...
  ..$ co2      : num [1:1000000] 878 878 878 878 878 ...
  ..$ h2o      : num [1:1000000] 4.66 4.66 4.66 4.66 4.66 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 2.26 2.29 2.29 2.31 2.29 ...
  ..$ press    : num [1:1000000] 101 101 102 101 101 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 2.37 2.47 2.47 2.56 2.56 ...
  ..$ e_hmp    : num [1:1000000] 0.652 0.656 0.656 0.661 0.661 ...
 $ 7 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 7000001 7000002 7000003 7000004 7000005 7000006 7000007 7000008 7000009 7000010 ...
  ..$ RECORD   : int [1:1000000] 768139393 768139394 768139395 768139396 768139397 768139398 768139399 768139400 768139401 768139402 ...
  ..$ Ux       : num [1:1000000] 2.03 1.224 1.423 0.726 0.981 ...
  ..$ Uy       : num [1:1000000] 4 4.15 5.25 4.3 4.73 ...
  ..$ Uz       : num [1:1000000] -1.327 -2.456 -0.168 -1.174 -0.492 ...
  ..$ co2      : num [1:1000000] 782 783 783 783 783 ...
  ..$ h2o      : num [1:1000000] 6.67 6.63 6.63 6.63 6.65 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 8.93 9.25 9.19 9.1 9.12 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 9.06 8.77 8.87 8.77 8.87 ...
  ..$ e_hmp    : num [1:1000000] 0.973 0.952 0.957 0.953 0.958 ...
 $ 8 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 8000001 8000002 8000003 8000004 8000005 8000006 8000007 8000008 8000009 8000010 ...
  ..$ RECORD   : int [1:1000000] 769139393 769139394 769139395 769139396 769139397 769139398 769139399 769139400 769139401 769139402 ...
  ..$ Ux       : num [1:1000000] 2.76 23.18 4 5.9 4.29 ...
  ..$ Uy       : num [1:1000000] 4.3 2.17 2.62 2.1 2.36 ...
  ..$ Uz       : num [1:1000000] -1.348 -6.32 -0.538 -1.056 -0.361 ...
  ..$ co2      : num [1:1000000] 1462 1469 1478 1472 1474 ...
  ..$ h2o      : num [1:1000000] 18.3 18.7 18.8 18.6 18.9 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 25.3 25.1 24 24.8 24 ...
  ..$ press    : num [1:1000000] 99.7 99.7 99.7 99.7 99.7 ...
  ..$ diag_csat: int [1:1000000] 7 7 3 3 3 3 3 3 7 3 ...
  ..$ t_hmp    : num [1:1000000] 10.02 9.92 10.02 9.92 10.02 ...
  ..$ e_hmp    : num [1:1000000] 1.2 1.2 1.2 1.19 1.2 ...
 $ 9 :'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 9000001 9000002 9000003 9000004 9000005 9000006 9000007 9000008 9000009 9000010 ...
  ..$ RECORD   : int [1:1000000] 770139393 770139394 770139395 770139396 770139397 770139398 770139399 770139400 770139401 770139402 ...
  ..$ Ux       : num [1:1000000] 2.42 1.81 1.84 2.3 1.12 ...
  ..$ Uy       : num [1:1000000] -1.36 -1.47 -1.19 -1.05 -1.37 ...
  ..$ Uz       : num [1:1000000] -0.184 -0.176 -0.14 0.397 0.282 ...
  ..$ co2      : num [1:1000000] 767 767 767 767 767 ...
  ..$ h2o      : num [1:1000000] 7.98 7.98 7.98 7.98 7.97 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 10.7 10.7 10.7 10.8 10.7 ...
  ..$ press    : num [1:1000000] 99.3 99.3 99.4 99.3 99.3 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 10.2 10.2 10.2 10.1 10 ...
  ..$ e_hmp    : num [1:1000000] 1.06 1.06 1.06 1.06 1.05 ...
 $ 10:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 10000001 10000002 10000003 10000004 10000005 10000006 10000007 10000008 10000009 10000010 ...
  ..$ RECORD   : int [1:1000000] 771139393 771139394 771139395 771139396 771139397 771139398 771139399 771139400 771139401 771139402 ...
  ..$ Ux       : num [1:1000000] -1.45 -1.45 -1.52 -1.54 -1.57 ...
  ..$ Uy       : num [1:1000000] -1.5 -1.46 -1.41 -1.4 -1.48 ...
  ..$ Uz       : num [1:1000000] -0.23 -0.196 -0.373 -0.342 -0.416 ...
  ..$ co2      : num [1:1000000] 4976 4949 4887 4835 4781 ...
  ..$ h2o      : num [1:1000000] 40.7 40.5 40 39.5 39.1 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 15.6 15.6 15.2 15.6 15.9 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: int [1:1000000] 1 1 1 1 1 1 1 0 0 1 ...
  ..$ t_hmp    : num [1:1000000] 5.28 5.38 5.28 5.28 5.28 ...
  ..$ e_hmp    : num [1:1000000] 0.853 0.859 0.853 0.853 0.854 ...
 $ 11:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 11000001 11000002 11000003 11000004 11000005 11000006 11000007 11000008 11000009 11000010 ...
  ..$ RECORD   : int [1:1000000] 772139393 772139394 772139395 772139396 772139397 772139398 772139399 772139400 772139401 772139402 ...
  ..$ Ux       : num [1:1000000] 0.684 0.704 0.688 0.687 0.686 ...
  ..$ Uy       : num [1:1000000] -0.171 -0.212 -0.231 -0.242 -0.233 ...
  ..$ Uz       : num [1:1000000] -0.0015 -0.0328 -0.002 0.0177 0.0245 ...
  ..$ co2      : num [1:1000000] 881 880 881 881 881 ...
  ..$ h2o      : num [1:1000000] 6.71 6.71 6.71 6.72 6.72 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 5.95 5.95 5.94 5.97 5.92 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 5.84 5.74 5.84 5.65 6.03 ...
  ..$ e_hmp    : num [1:1000000] 0.882 0.878 0.882 0.872 0.896 ...
 $ 12:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 12000001 12000002 12000003 12000004 12000005 12000006 12000007 12000008 12000009 12000010 ...
  ..$ RECORD   : int [1:1000000] 773139393 773139394 773139395 773139396 773139397 773139398 773139399 773139400 773139401 773139402 ...
  ..$ Ux       : num [1:1000000] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
  ..$ Uy       : num [1:1000000] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
  ..$ Uz       : num [1:1000000] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
  ..$ co2      : num [1:1000000] 977 979 967 973 977 ...
  ..$ h2o      : num [1:1000000] 20.7 20.9 20.5 20.8 21 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
  ..$ press    : num [1:1000000] 99.9 99.8 99.8 99.8 99.9 ...
  ..$ diag_csat: int [1:1000000] 61503 61503 61503 61503 61503 61503 61503 61503 61503 61503 ...
  ..$ t_hmp    : num [1:1000000] 10 10 10.1 10 10.1 ...
  ..$ e_hmp    : num [1:1000000] 1.23 1.23 1.24 1.23 1.24 ...
 $ 13:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 13000001 13000002 13000003 13000004 13000005 13000006 13000007 13000008 13000009 13000010 ...
  ..$ RECORD   : int [1:1000000] 774139393 774139394 774139395 774139396 774139397 774139398 774139399 774139400 774139401 774139402 ...
  ..$ Ux       : num [1:1000000] 2.05 2.18 1.48 1.7 1.83 ...
  ..$ Uy       : num [1:1000000] 0.8 0.833 1.389 1.44 1.54 ...
  ..$ Uz       : num [1:1000000] -0.403 -0.406 -0.608 -0.825 -0.631 ...
  ..$ co2      : num [1:1000000] 778 778 777 777 777 ...
  ..$ h2o      : num [1:1000000] 5.74 5.75 5.75 5.75 5.75 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 6.05 6.13 6.08 6.08 6.05 ...
  ..$ press    : num [1:1000000] 99.7 99.7 99.7 99.7 99.7 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 6.48 6.38 6.48 6.67 6.57 ...
  ..$ e_hmp    : num [1:1000000] 0.779 0.775 0.779 0.792 0.785 ...
 $ 14:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 14000001 14000002 14000003 14000004 14000005 14000006 14000007 14000008 14000009 14000010 ...
  ..$ RECORD   : int [1:1000000] 775139393 775139394 775139395 775139396 775139397 775139398 775139399 775139400 775139401 775139402 ...
  ..$ Ux       : num [1:1000000] 14.33 13.92 1.13 12.96 14.26 ...
  ..$ Uy       : num [1:1000000] 3.56 1.4 4.01 4.11 3.97 ...
  ..$ Uz       : num [1:1000000] -2.063 -0.582 1.562 -2.656 -1.658 ...
  ..$ co2      : num [1:1000000] 1581 1581 1599 1609 1615 ...
  ..$ h2o      : num [1:1000000] 19.1 19.2 19.3 19.3 19.3 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 16.5 15.8 18.2 18.6 18.8 ...
  ..$ press    : num [1:1000000] 98.5 98.5 98.5 98.5 98.5 ...
  ..$ diag_csat: int [1:1000000] 7 7 3 7 7 7 7 7 7 3 ...
  ..$ t_hmp    : num [1:1000000] 11.5 11.8 11.5 11.6 11.5 ...
  ..$ e_hmp    : num [1:1000000] 1.33 1.36 1.33 1.34 1.33 ...
 $ 15:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 15000001 15000002 15000003 15000004 15000005 15000006 15000007 15000008 15000009 15000010 ...
  ..$ RECORD   : int [1:1000000] 776139393 776139394 776139395 776139396 776139397 776139398 776139399 776139400 776139401 776139402 ...
  ..$ Ux       : num [1:1000000] 5.81 7 5.82 5.21 5.46 ...
  ..$ Uy       : num [1:1000000] 8.88 7.6 9.12 9.07 9.19 ...
  ..$ Uz       : num [1:1000000] 0.0715 -0.0232 -0.576 0.0798 0.6383 ...
  ..$ co2      : num [1:1000000] 864 857 861 858 862 ...
  ..$ h2o      : num [1:1000000] 7.33 7.24 7.29 7.34 7.29 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 8.94 8.81 8.93 8.72 8.75 ...
  ..$ press    : num [1:1000000] 99.3 99.3 99.3 99.2 99.3 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 8.59 8.49 8.69 8.49 8.59 ...
  ..$ e_hmp    : num [1:1000000] 0.989 0.985 0.996 0.986 0.988 ...
 $ 16:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 16000001 16000002 16000003 16000004 16000005 16000006 16000007 16000008 16000009 16000010 ...
  ..$ RECORD   : int [1:1000000] 777139393 777139394 777139395 777139396 777139397 777139398 777139399 777139400 777139401 777139402 ...
  ..$ Ux       : num [1:1000000] 4.51 6.39 2.82 3.48 5.6 ...
  ..$ Uy       : num [1:1000000] 6.61 6.8 6.37 7.83 7.95 ...
  ..$ Uz       : num [1:1000000] 1.37 1.19 3.4 1.41 1.34 ...
  ..$ co2      : num [1:1000000] 852 852 851 852 853 ...
  ..$ h2o      : num [1:1000000] 9.6 9.63 9.6 9.59 9.62 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 12.7 13 12.8 13.1 12.9 ...
  ..$ press    : num [1:1000000] 98.8 98.8 98.8 98.8 98.8 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 11.8 11.9 11.8 11.9 11.8 ...
  ..$ e_hmp    : num [1:1000000] 1.32 1.32 1.32 1.32 1.32 ...
 $ 17:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 17000001 17000002 17000003 17000004 17000005 17000006 17000007 17000008 17000009 17000010 ...
  ..$ RECORD   : int [1:1000000] 778139393 778139394 778139395 778139396 778139397 778139398 778139399 778139400 778139401 778139402 ...
  ..$ Ux       : num [1:1000000] 0.83 1.202 1.133 0.59 0.249 ...
  ..$ Uy       : num [1:1000000] -1.25 -1.3 -2.31 -2.63 -2.49 ...
  ..$ Uz       : num [1:1000000] 0.345 0.173 0.015 0.798 1.36 ...
  ..$ co2      : num [1:1000000] 835 835 836 836 836 ...
  ..$ h2o      : num [1:1000000] 4.63 4.63 4.63 4.62 4.63 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 3.41 3.35 3.3 3.31 3.41 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ t_hmp    : num [1:1000000] 3.59 3.5 3.59 3.5 3.5 ...
  ..$ e_hmp    : num [1:1000000] 0.682 0.677 0.681 0.678 0.676 ...
 $ 18:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 18000001 18000002 18000003 18000004 18000005 18000006 18000007 18000008 18000009 18000010 ...
  ..$ RECORD   : int [1:1000000] 779139393 779139394 779139395 779139396 779139397 779139398 779139399 779139400 779139401 779139402 ...
  ..$ Ux       : num [1:1000000] 3.62 5.38 3.07 4.98 4.89 ...
  ..$ Uy       : num [1:1000000] 3.11 4.38 3.52 2.82 3.56 ...
  ..$ Uz       : num [1:1000000] 0.434 0.292 1.078 1.3845 -0.0757 ...
  ..$ co2      : num [1:1000000] 1261 1258 1253 1247 1245 ...
  ..$ h2o      : num [1:1000000] 16.3 16.2 16.2 16 15.9 ...
  ..$ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
  ..$ Ts       : num [1:1000000] 21.1 20.6 17.7 20.3 19.5 ...
  ..$ press    : num [1:1000000] 98 98 98 98 98 ...
  ..$ diag_csat: int [1:1000000] 2 2 3 3 3 2 3 2 3 3 ...
  ..$ t_hmp    : num [1:1000000] 10.2 10.1 10.5 10.2 10.4 ...
  ..$ e_hmp    : num [1:1000000] 1.2 1.2 1.23 1.21 1.22 ...
 $ 19:'data.frame':	1000000 obs. of  13 variables:
  ..$ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 19000001 19000002 19000003 19000004 19000005 19000006 19000007 19000008 19000009 19000010 ...

In [12]:
str(data_split[[1]])

'data.frame':	1000000 obs. of  13 variables:
 $ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ RECORD   : int  761139393 761139394 761139395 761139396 761139397 761139398 761139399 761139400 761139401 761139402 ...
 $ Ux       : num  1.69 1.55 1.52 1.96 1.36 ...
 $ Uy       : num  0.69 0.163 -0.111 -0.344 -0.455 ...
 $ Uz       : num  0.864 1.363 1.746 0.639 1.206 ...
 $ co2      : num  761 760 760 761 761 ...
 $ h2o      : num  8.81 8.79 8.79 8.81 8.81 ...
 $ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
 $ Ts       : num  12.1 12.1 12.2 12.1 12.1 ...
 $ press    : num  99.3 99.2 99.2 99.2 99.3 ...
 $ diag_csat: int  0 0 0 0 0 0 0 0 0 0 ...
 $ t_hmp    : num  11.5 11.5 11.8 11.6 11.7 ...
 $ e_hmp    : num  1.22 1.22 1.25 1.23 1.24 ...

In [24]:
str(data_split[[29]])

'data.frame':	501657 obs. of  13 variables:
 $ TIMESTAMP: Factor w/ 28501657 levels "2014-12-22 11:47:39.3",..: 28000001 28000002 28000003 28000004 28000005 28000006 28000007 28000008 28000009 28000010 ...
 $ RECORD   : int  789139393 789139394 789139395 789139396 789139397 789139398 789139399 789139400 789139401 789139402 ...
 $ Ux       : num  1.88 1.94 1.9 2.19 2.72 ...
 $ Uy       : num  -1.31 -1.21 -1 -1.62 -1.08 ...
 $ Uz       : num  -0.233 -0.294 -0.421 -0.704 -0.776 ...
 $ co2      : num  793 794 794 794 794 ...
 $ h2o      : num  5.77 5.78 5.78 5.8 5.8 ...
 $ n2o      : Factor w/ 1 level "NAN": 1 1 1 1 1 1 1 1 1 1 ...
 $ Ts       : num  6.09 6.03 6.07 6.07 6.01 ...
 $ press    : num  99.7 99.8 99.8 99.8 99.8 ...
 $ diag_csat: int  0 0 0 0 0 0 0 0 0 0 ...
 $ t_hmp    : num  5.96 5.96 5.96 5.96 5.96 ...
 $ e_hmp    : num  0.758 0.759 0.759 0.759 0.759 ...

In [45]:
head(data_split[[1]])

  TIMESTAMP             RECORD    Ux      Uy         Uz        co2
1 2014-12-22 11:47:39.3 761139393 1.69375  0.6897500 0.8642501 760.7380
2 2014-12-22 11:47:39.4 761139394 1.55100  0.1625000 1.3627500 760.2671
3 2014-12-22 11:47:39.5 761139395 1.51725 -0.1107500 1.7462500 760.1978
4 2014-12-22 11:47:39.6 761139396 1.95925 -0.3437500 0.6390001 760.7865
5 2014-12-22 11:47:39.7 761139397 1.36050 -0.4550000 1.2060000 760.8245
6 2014-12-22 11:47:39.8 761139398 0.57650 -0.9160001 1.2277500 760.9031
  h2o      n2o Ts       press    diag_csat t_hmp    e_hmp
1 8.811520 NAN 12.08542 99.28229 0         11.51643 1.219314
2 8.790375 NAN 12.10226 99.24676 0         11.51643 1.220242
3 8.794267 NAN 12.16629 99.24676 0         11.80331 1.245500
4 8.813287 NAN 12.07193 99.24676 0         11.61206 1.227055
5 8.806199 NAN 12.12418 99.25624 0         11.70769 1.235777
6 8.796409 NAN 12.12582 99.22072 0         11.70769 1.236716

In [46]:
head(data_split[[29]])

         TIMESTAMP             RECORD    Ux      Uy       Uz         co2
28000001 2015-01-23 21:34:19.3 789139393 1.88225 -1.31275 -0.2332500 793.3365
28000002 2015-01-23 21:34:19.4 789139394 1.93700 -1.20600 -0.2942500 793.7191
28000003 2015-01-23 21:34:19.5 789139395 1.89800 -1.00475 -0.4210000 793.7352
28000004 2015-01-23 21:34:19.6 789139396 2.19450 -1.62500 -0.7040001 793.5444
28000005 2015-01-23 21:34:19.7 789139397 2.71700 -1.07950 -0.7765000 793.8083
28000006 2015-01-23 21:34:19.8 789139398 2.63100 -0.65525 -0.2002500 793.7773
         h2o      n2o Ts       press    diag_csat t_hmp    e_hmp
28000001 5.768875 NAN 6.093353 99.74144 0         5.962234 0.7584324
28000002 5.775090 NAN 6.031708 99.75114 0         5.962234 0.7590697
28000003 5.782685 NAN 6.065033 99.75114 0         5.962234 0.7590697
28000004 5.796525 NAN 6.068390 99.75114 0         5.962234 0.7590697
28000005 5.795643 NAN 6.005035 99.75114 0         5.962234 0.7590697
28000006 5.798342 NAN 6.101715 99.74144 0         6.249413 0.7768880

In [17]:
nrow(data_split[[1]])

[1] 1000000

In [19]:
nrow(data_split[[29]])

[1] 501657

In [43]:
# save each chunk as a new CSV file
for (n in seq_along(data_split)) {
  write.table(
    data_split[[n]],
    paste(
      "data/CSV/TOA5_2806.", "ts_data.", sprintf("%02d", n), ".csv", sep = ""
    ),
    row.names = FALSE, sep = ",", quote = FALSE
  )
}

## TOA5_1541.ts_data.dat

Split TOA5 file (~28 mil rows, 2.6 GB) into max. 1 mil row files

In [21]:
system("sed -n '1,7p' 'data/TOA5/TOA5_1541.ts_data.dat'", intern = TRUE)

[1] "\"TOA5\",\"1541\",\"CR5000\",\"1541\",\"2.3\",\"CPU:3D_LI_EB_DFnew.CR5\",\"52197\",\"ts_data\"\r"
[2] "\"TIMESTAMP\",\"RECORD\",\"Ux\",\"Uy\",\"Uz\",\"co2\",\"h2o\",\"Ts\",\"press\",\"diag_csat\",\"diag_irga\"\r"
[3] "\"TS\",\"RN\",\"m/s\",\"m/s\",\"m/s\",\"mg/(m^3)\",\"g/(m^3)\",\"C\",\"kPa\",\"unitless\",\"unitless\"\r"
[4] "\"\",\"\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\"\r"
[5] "\"2014-12-22 11:34:40.5\",0,7.625,-0.60975,-1.09925,679.6425,6.929612,11.20652,99.57032,0,0\r"
[6] "\"2014-12-22 11:34:40.6\",1,8.6485,-1.2965,-0.332,679.6145,6.925771,11.27213,99.57032,0,0\r"
[7] "\"2014-12-22 11:34:40.7\",2,6.9455,-0.5362501,1.85525,679.9779,6.920726,11.40673,99.57032,0,0\r"

In [1]:
data <- read.csv("data/TOA5/TOA5_1541.ts_data.dat", skip = 4, header = FALSE)

In [3]:
headers <- read.csv(
  "data/TOA5/TOA5_1541.ts_data.dat", skip = 1, header = FALSE, nrows = 3
)

In [4]:
headers

  V1        V2     V3  V4  V5  V6       V7      V8  V9    V10       V11
1 TIMESTAMP RECORD Ux  Uy  Uz  co2      h2o     Ts  press diag_csat diag_irga
2 TS        RN     m/s m/s m/s mg/(m^3) g/(m^3) C   kPa   unitless  unitless
3                  Smp Smp Smp Smp      Smp     Smp Smp   Smp       Smp

In [5]:
write.table(
  headers, "data/CSV/TOA5_1541.ts_data.headers.csv", row.names = FALSE,
  col.names = FALSE, sep = ",", quote = FALSE
)

In [6]:
names(data) <- as.matrix(
  read.csv(
    "data/TOA5/TOA5_1541.ts_data.dat", skip = 1, header = FALSE, nrows = 1
  )
)

In [7]:
head(data)

  TIMESTAMP             RECORD Ux       Uy         Uz         co2      h2o
1 2014-12-22 11:34:40.5 0      7.625000 -0.6097500 -1.0992500 679.6425 6.929612
2 2014-12-22 11:34:40.6 1      8.648500 -1.2965000 -0.3320000 679.6145 6.925771
3 2014-12-22 11:34:40.7 2      6.945500 -0.5362501  1.8552500 679.9779 6.920726
4 2014-12-22 11:34:40.8 3      5.967500  0.0405000  2.4327500 679.7805 6.925632
5 2014-12-22 11:34:40.9 4      6.414250 -1.2317500  0.9755000 679.8032 6.919812
6 2014-12-22 11:34:41   5      8.913501  1.6460000  0.9875001 679.8406 6.957347
  Ts       press    diag_csat diag_irga
1 11.20652 99.57032 0         0
2 11.27213 99.57032 0         0
3 11.40673 99.57032 0         0
4 11.24857 99.57032 0         0
5 11.25699 99.53477 0         0
6 11.82599 99.53477 0         0

In [8]:
summary(data)

                 TIMESTAMP            RECORD               Ux
 2014-12-22 11:34:40.5:       1   Min.   :       0   Min.   :-65.53
 2014-12-22 11:34:40.6:       1   1st Qu.: 7121824   1st Qu.:  0.35
 2014-12-22 11:34:40.7:       1   Median :14243648   Median :  1.25
 2014-12-22 11:34:40.8:       1   Mean   :14243648   Mean   :  1.82
 2014-12-22 11:34:40.9:       1   3rd Qu.:21365471   3rd Qu.:  2.91
 2014-12-22 11:34:41  :       1   Max.   :28487295   Max.   : 65.53
 (Other)              :28487290                      NA's   :104082
       Uy               Uz              co2               h2o
 Min.   :-65.53   Min.   :-40.70   Min.   :-7014.9   Min.   : -3.588
 1st Qu.: -0.99   1st Qu.: -0.27   1st Qu.:  706.7   1st Qu.:  3.647
 Median :  0.08   Median :  0.03   Median :  728.5   Median :  4.827
 Mean   :  0.23   Mean   :  0.07   Mean   :  848.0   Mean   :  6.664
 3rd Qu.:  1.46   3rd Qu.:  0.41   3rd Qu.:  908.0   3rd Qu.:  8.177
 Max.   : 65.53   Max.   : 41.89   Max.   :67855.1   Max.   :466.886
 NA's   :104082   NA's   :104082
       Ts             press          diag_csat          diag_irga
 Min.   :-38.26   Min.   : 95.27   0      :24263578   Min.   :0
 1st Qu.:  2.87   1st Qu.: 99.10   1      : 1926069   1st Qu.:0
 Median :  5.69   Median : 99.73   2      :  942522   Median :0
 Mean   :  7.89   Mean   : 99.65   3      :  917123   Mean   :0
 3rd Qu.: 11.43   3rd Qu.:100.34   15     :  150168   3rd Qu.:0
 Max.   : 72.63   Max.   :102.04   7      :   77561   Max.   :0
 NA's   :104082                    (Other):  210275

In [9]:
nrow(data)

[1] 28487296

In [10]:
data_split <- split(data, (as.numeric(rownames(data)) - 1) %/% 1000000)

In [11]:
str(data_split)

List of 29
 $ 0 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 1 2 3 4 5 6 7 8 9 10 ...
  ..$ RECORD   : int [1:1000000] 0 1 2 3 4 5 6 7 8 9 ...
  ..$ Ux       : num [1:1000000] 7.62 8.65 6.95 5.97 6.41 ...
  ..$ Uy       : num [1:1000000] -0.6098 -1.2965 -0.5363 0.0405 -1.2317 ...
  ..$ Uz       : num [1:1000000] -1.099 -0.332 1.855 2.433 0.976 ...
  ..$ co2      : num [1:1000000] 680 680 680 680 680 ...
  ..$ h2o      : num [1:1000000] 6.93 6.93 6.92 6.93 6.92 ...
  ..$ Ts       : num [1:1000000] 11.2 11.3 11.4 11.2 11.3 ...
  ..$ press    : num [1:1000000] 99.6 99.6 99.6 99.6 99.5 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 1 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 1000001 1000002 1000003 1000004 1000005 1000006 1000007 1000008 1000009 1000010 ...
  ..$ RECORD   : int [1:1000000] 1000000 1000001 1000002 1000003 1000004 1000005 1000006 1000007 1000008 1000009 ...
  ..$ Ux       : num [1:1000000] 2.8 3.03 1.84 3.36 4.8 ...
  ..$ Uy       : num [1:1000000] 0.487 1.54 0.572 1.2 1.242 ...
  ..$ Uz       : num [1:1000000] 0.468 1.518 1.482 2.189 0.106 ...
  ..$ co2      : num [1:1000000] 1202 1204 1201 1202 1198 ...
  ..$ h2o      : num [1:1000000] 16.6 16.6 16.6 16.5 16.4 ...
  ..$ Ts       : num [1:1000000] 23.1 21.8 21 20.3 20.3 ...
  ..$ press    : num [1:1000000] 98.8 98.8 98.8 98.8 98.8 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 10 9 9 9 9 9 9 10 9 10 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 2 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 2000001 2000002 2000003 2000004 2000005 2000006 2000007 2000008 2000009 2000010 ...
  ..$ RECORD   : int [1:1000000] 2000000 2000001 2000002 2000003 2000004 2000005 2000006 2000007 2000008 2000009 ...
  ..$ Ux       : num [1:1000000] 1.043 0.925 0.737 0.683 0.526 ...
  ..$ Uy       : num [1:1000000] -0.399 -0.371 -0.312 -0.264 -0.151 ...
  ..$ Uz       : num [1:1000000] 0.43 0.699 0.57 0.564 0.426 ...
  ..$ co2      : num [1:1000000] 732 732 731 731 731 ...
  ..$ h2o      : num [1:1000000] 4.1 4.09 4.1 4.09 4.1 ...
  ..$ Ts       : num [1:1000000] 3.87 3.88 3.92 3.91 3.91 ...
  ..$ press    : num [1:1000000] 100 101 100 100 100 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 3 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 3000001 3000002 3000003 3000004 3000005 3000006 3000007 3000008 3000009 3000010 ...
  ..$ RECORD   : int [1:1000000] 3000000 3000001 3000002 3000003 3000004 3000005 3000006 3000007 3000008 3000009 ...
  ..$ Ux       : num [1:1000000] 0.344 0.363 0.324 0.401 0.419 ...
  ..$ Uy       : num [1:1000000] -0.474 -0.479 -0.497 -0.581 -0.567 ...
  ..$ Uz       : num [1:1000000] 0.0005 0.00875 -0.041 -0.0395 -0.0375 ...
  ..$ co2      : num [1:1000000] 731 731 732 732 732 ...
  ..$ h2o      : num [1:1000000] 3.79 3.8 3.8 3.8 3.8 ...
  ..$ Ts       : num [1:1000000] 3.38 3.36 3.33 3.29 3.29 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 4 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 4000001 4000002 4000003 4000004 4000005 4000006 4000007 4000008 4000009 4000010 ...
  ..$ RECORD   : int [1:1000000] 4000000 4000001 4000002 4000003 4000004 4000005 4000006 4000007 4000008 4000009 ...
  ..$ Ux       : num [1:1000000] 0.424 0.435 0.587 0.555 0.591 ...
  ..$ Uy       : num [1:1000000] -0.798 -0.695 -0.623 -0.6 -0.62 ...
  ..$ Uz       : num [1:1000000] 0.28 0.291 0.239 0.214 0.279 ...
  ..$ co2      : num [1:1000000] 708 708 709 708 709 ...
  ..$ h2o      : num [1:1000000] 4.4 4.4 4.41 4.41 4.41 ...
  ..$ Ts       : num [1:1000000] 4.27 4.31 4.33 4.37 4.32 ...
  ..$ press    : num [1:1000000] 99.8 99.8 99.8 99.8 99.8 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 5 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 5000001 5000002 5000003 5000004 5000005 5000006 5000007 5000008 5000009 5000010 ...
  ..$ RECORD   : int [1:1000000] 5000000 5000001 5000002 5000003 5000004 5000005 5000006 5000007 5000008 5000009 ...
  ..$ Ux       : num [1:1000000] -0.534 -0.36 -0.39 -0.354 -0.368 ...
  ..$ Uy       : num [1:1000000] -1.514 -1.394 -0.992 -0.869 -0.93 ...
  ..$ Uz       : num [1:1000000] 0.498 0.667 0.512 0.508 0.546 ...
  ..$ co2      : num [1:1000000] 739 738 738 738 739 ...
  ..$ h2o      : num [1:1000000] 2.81 2.82 2.82 2.82 2.81 ...
  ..$ Ts       : num [1:1000000] -0.62 -0.57 -0.611 -0.585 -0.641 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 6 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 6000001 6000002 6000003 6000004 6000005 6000006 6000007 6000008 6000009 6000010 ...
  ..$ RECORD   : int [1:1000000] 6000000 6000001 6000002 6000003 6000004 6000005 6000006 6000007 6000008 6000009 ...
  ..$ Ux       : num [1:1000000] 0.537 0.533 0.578 0.516 0.488 ...
  ..$ Uy       : num [1:1000000] 0.418 0.493 0.414 0.463 0.485 ...
  ..$ Uz       : num [1:1000000] -0.072 -0.009 -0.035 -0.0345 -0.0777 ...
  ..$ co2      : num [1:1000000] 758 758 758 759 758 ...
  ..$ h2o      : num [1:1000000] 3.38 3.38 3.38 3.38 3.38 ...
  ..$ Ts       : num [1:1000000] 1.71 1.72 1.73 1.72 1.75 ...
  ..$ press    : num [1:1000000] 102 102 102 102 102 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 7 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 7000001 7000002 7000003 7000004 7000005 7000006 7000007 7000008 7000009 7000010 ...
  ..$ RECORD   : int [1:1000000] 7000000 7000001 7000002 7000003 7000004 7000005 7000006 7000007 7000008 7000009 ...
  ..$ Ux       : num [1:1000000] 5.92 4.97 4.6 2.74 4.08 ...
  ..$ Uy       : num [1:1000000] 1.86 2.9 3.05 3.56 3.84 ...
  ..$ Uz       : num [1:1000000] -0.114 0.566 -0.241 1.236 0.799 ...
  ..$ co2      : num [1:1000000] 693 693 693 693 694 ...
  ..$ h2o      : num [1:1000000] 5.2 5.19 5.22 5.23 5.18 ...
  ..$ Ts       : num [1:1000000] 8.13 8.18 8.4 8.22 8.09 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 8 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 8000001 8000002 8000003 8000004 8000005 8000006 8000007 8000008 8000009 8000010 ...
  ..$ RECORD   : int [1:1000000] 8000000 8000001 8000002 8000003 8000004 8000005 8000006 8000007 8000008 8000009 ...
  ..$ Ux       : num [1:1000000] 2.43 2.58 3.04 2.62 2.54 ...
  ..$ Uy       : num [1:1000000] 1.96 2.06 1.23 1.23 1.52 ...
  ..$ Uz       : num [1:1000000] 0.452 0.367 0.344 0.458 0.596 ...
  ..$ co2      : num [1:1000000] 1184 1186 1186 1186 1186 ...
  ..$ h2o      : num [1:1000000] 22.9 23 22.9 22.9 22.9 ...
  ..$ Ts       : num [1:1000000] 25.2 24.3 25.3 23.7 24.5 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 10 9 10 9 1 10 9 9 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 9 :'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 9000001 9000002 9000003 9000004 9000005 9000006 9000007 9000008 9000009 9000010 ...
  ..$ RECORD   : int [1:1000000] 9000000 9000001 9000002 9000003 9000004 9000005 9000006 9000007 9000008 9000009 ...
  ..$ Ux       : num [1:1000000] -0.364 -0.453 -0.491 -0.276 -0.447 ...
  ..$ Uy       : num [1:1000000] -2.27 -2.04 -1.82 -2.06 -1.5 ...
  ..$ Uz       : num [1:1000000] 0.887 0.908 0.886 0.938 1.293 ...
  ..$ co2      : num [1:1000000] 695 695 695 695 695 ...
  ..$ h2o      : num [1:1000000] 5.42 5.43 5.42 5.4 5.42 ...
  ..$ Ts       : num [1:1000000] 8.57 8.6 8.61 8.64 8.62 ...
  ..$ press    : num [1:1000000] 99.8 99.8 99.8 99.8 99.8 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 10:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 10000001 10000002 10000003 10000004 10000005 10000006 10000007 10000008 10000009 10000010 ...
  ..$ RECORD   : int [1:1000000] 10000000 10000001 10000002 10000003 10000004 10000005 10000006 10000007 10000008 10000009 ...
  ..$ Ux       : num [1:1000000] -0.432 -0.29 -0.282 -0.447 -0.417 ...
  ..$ Uy       : num [1:1000000] 0.367 0.398 0.348 0.342 0.383 ...
  ..$ Uz       : num [1:1000000] -0.334 -0.334 -0.311 -0.258 -0.287 ...
  ..$ co2      : num [1:1000000] 1871 1866 1861 1858 1855 ...
  ..$ h2o      : num [1:1000000] 19.2 19.2 19.1 19.1 19 ...
  ..$ Ts       : num [1:1000000] 4.57 4.56 4.62 4.58 4.57 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 11:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 11000001 11000002 11000003 11000004 11000005 11000006 11000007 11000008 11000009 11000010 ...
  ..$ RECORD   : int [1:1000000] 11000000 11000001 11000002 11000003 11000004 11000005 11000006 11000007 11000008 11000009 ...
  ..$ Ux       : num [1:1000000] 0.866 0.838 0.804 0.792 0.775 ...
  ..$ Uy       : num [1:1000000] -0.1113 -0.1065 -0.0737 -0.092 -0.1115 ...
  ..$ Uz       : num [1:1000000] -0.128 -0.128 -0.121 -0.122 -0.121 ...
  ..$ co2      : num [1:1000000] 757 757 756 757 756 ...
  ..$ h2o      : num [1:1000000] 5.14 5.15 5.14 5.15 5.15 ...
  ..$ Ts       : num [1:1000000] 5.28 5.3 5.25 5.27 5.28 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 12:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 12000001 12000002 12000003 12000004 12000005 12000006 12000007 12000008 12000009 12000010 ...
  ..$ RECORD   : int [1:1000000] 12000000 12000001 12000002 12000003 12000004 12000005 12000006 12000007 12000008 12000009 ...
  ..$ Ux       : num [1:1000000] 2.9 2.58 2.59 3.37 3.46 ...
  ..$ Uy       : num [1:1000000] 3.43 3.48 3.54 3.54 3.46 ...
  ..$ Uz       : num [1:1000000] 0.17 0.465 0.605 0.272 0.423 ...
  ..$ co2      : num [1:1000000] 924 926 925 926 925 ...
  ..$ h2o      : num [1:1000000] 9.43 9.45 9.43 9.42 9.41 ...
  ..$ Ts       : num [1:1000000] 20.4 20.4 20.8 20.7 20.6 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 13:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 13000001 13000002 13000003 13000004 13000005 13000006 13000007 13000008 13000009 13000010 ...
  ..$ RECORD   : int [1:1000000] 13000000 13000001 13000002 13000003 13000004 13000005 13000006 13000007 13000008 13000009 ...
  ..$ Ux       : num [1:1000000] 0.665 0.92 1.085 1.377 1.56 ...
  ..$ Uy       : num [1:1000000] 0.617 0.684 1.116 0.951 0.484 ...
  ..$ Uz       : num [1:1000000] -0.154 0.225 0.179 0.226 0.215 ...
  ..$ co2      : num [1:1000000] 695 694 694 695 695 ...
  ..$ h2o      : num [1:1000000] 4.31 4.31 4.31 4.31 4.3 ...
  ..$ Ts       : num [1:1000000] 5.85 5.75 5.65 5.68 5.67 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 14:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 14000001 14000002 14000003 14000004 14000005 14000006 14000007 14000008 14000009 14000010 ...
  ..$ RECORD   : int [1:1000000] 14000000 14000001 14000002 14000003 14000004 14000005 14000006 14000007 14000008 14000009 ...
  ..$ Ux       : num [1:1000000] 2.96 2.21 3.64 5.17 3.54 ...
  ..$ Uy       : num [1:1000000] 1.18 2.24 2.39 0.06 2.36 ...
  ..$ Uz       : num [1:1000000] 1.18 1.36 1.44 1.91 1.22 ...
  ..$ co2      : num [1:1000000] 1086 1081 1079 1082 1083 ...
  ..$ h2o      : num [1:1000000] 12.7 12.6 12.6 12.6 12.6 ...
  ..$ Ts       : num [1:1000000] 20.8 21 21.3 20.5 20.5 ...
  ..$ press    : num [1:1000000] 98.8 98.8 98.8 98.8 98.8 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 2 1 1 2 2 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 15:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 15000001 15000002 15000003 15000004 15000005 15000006 15000007 15000008 15000009 15000010 ...
  ..$ RECORD   : int [1:1000000] 15000000 15000001 15000002 15000003 15000004 15000005 15000006 15000007 15000008 15000009 ...
  ..$ Ux       : num [1:1000000] 5.3 7.5 21.09 8.79 5.67 ...
  ..$ Uy       : num [1:1000000] 2.265 0.133 1.113 -0.129 0.269 ...
  ..$ Uz       : num [1:1000000] 1.83 2.45 -1.37 1.69 2.39 ...
  ..$ co2      : num [1:1000000] 1417 1387 1394 1398 1410 ...
  ..$ h2o      : num [1:1000000] 13.7 13.7 13.9 14.1 14 ...
  ..$ Ts       : num [1:1000000] 17.5 17.4 22.8 18 16.4 ...
  ..$ press    : num [1:1000000] 99.8 99.8 99.7 99.8 99.8 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 9 9 8 10 10 9 9 10 9 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 16:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 16000001 16000002 16000003 16000004 16000005 16000006 16000007 16000008 16000009 16000010 ...
  ..$ RECORD   : int [1:1000000] 16000000 16000001 16000002 16000003 16000004 16000005 16000006 16000007 16000008 16000009 ...
  ..$ Ux       : num [1:1000000] 6.49 6.85 7.15 7.08 6.77 ...
  ..$ Uy       : num [1:1000000] 2.61 1.1 1.68 2.53 2.22 ...
  ..$ Uz       : num [1:1000000] -2.01 -1.48 -1.83 -1.88 -1.39 ...
  ..$ co2      : num [1:1000000] 781 781 782 782 783 ...
  ..$ h2o      : num [1:1000000] 8.31 8.34 8.36 8.36 8.34 ...
  ..$ Ts       : num [1:1000000] 12 12 11.7 11.8 11.9 ...
  ..$ press    : num [1:1000000] 99.1 99.1 99.1 99.1 99.1 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 17:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 17000001 17000002 17000003 17000004 17000005 17000006 17000007 17000008 17000009 17000010 ...
  ..$ RECORD   : int [1:1000000] 17000000 17000001 17000002 17000003 17000004 17000005 17000006 17000007 17000008 17000009 ...
  ..$ Ux       : num [1:1000000] 1.13 1.61 1.51 1.42 1.24 ...
  ..$ Uy       : num [1:1000000] 0.396 0.211 0.0527 0.307 0.2268 ...
  ..$ Uz       : num [1:1000000] 0.1437 -0.1313 -0.1832 -0.0935 -0.2328 ...
  ..$ co2      : num [1:1000000] 722 722 722 722 722 ...
  ..$ h2o      : num [1:1000000] 3.36 3.36 3.36 3.36 3.35 ...
  ..$ Ts       : num [1:1000000] 2.75 2.71 2.75 2.78 2.99 ...
  ..$ press    : num [1:1000000] 100 100 100 100 100 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 1 1 1 1 1 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 18:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 18000001 18000002 18000003 18000004 18000005 18000006 18000007 18000008 18000009 18000010 ...
  ..$ RECORD   : int [1:1000000] 18000000 18000001 18000002 18000003 18000004 18000005 18000006 18000007 18000008 18000009 ...
  ..$ Ux       : num [1:1000000] 4.12 3.24 2.58 2.02 2.77 ...
  ..$ Uy       : num [1:1000000] 0.449 0.666 0.671 0.747 -0.253 ...
  ..$ Uz       : num [1:1000000] 0.287 1.55 1.564 1.775 1.696 ...
  ..$ co2      : num [1:1000000] 833 831 832 832 833 ...
  ..$ h2o      : num [1:1000000] 9.08 9.03 9.18 9.1 9.18 ...
  ..$ Ts       : num [1:1000000] 19.3 15.7 16.9 16.8 15.6 ...
  ..$ press    : num [1:1000000] 98.4 98.5 98.5 98.5 98.4 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 2 10 9 10 10 9 10 10 9 9 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 19:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 19000001 19000002 19000003 19000004 19000005 19000006 19000007 19000008 19000009 19000010 ...
  ..$ RECORD   : int [1:1000000] 19000000 19000001 19000002 19000003 19000004 19000005 19000006 19000007 19000008 19000009 ...
  ..$ Ux       : num [1:1000000] 7.12 2.01 1.75 2.11 2.36 ...
  ..$ Uy       : num [1:1000000] 1.044 1.22 1.301 1.349 0.879 ...
  ..$ Uz       : num [1:1000000] -1.3742 0.1435 0.0607 0.0398 -0.0122 ...
  ..$ co2      : num [1:1000000] 1000 1001 1003 1001 1004 ...
  ..$ h2o      : num [1:1000000] 5.47 5.46 5.5 5.5 5.5 ...
  ..$ Ts       : num [1:1000000] 0.71 2.69 2.22 2.05 2.18 ...
  ..$ press    : num [1:1000000] 98 98 98 98 98 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 2 10 10 10 10 10 2 2 10 10 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 20:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 20000001 20000002 20000003 20000004 20000005 20000006 20000007 20000008 20000009 20000010 ...
  ..$ RECORD   : int [1:1000000] 20000000 20000001 20000002 20000003 20000004 20000005 20000006 20000007 20000008 20000009 ...
  ..$ Ux       : num [1:1000000] 0.918 1.722 2.192 2.302 3.102 ...
  ..$ Uy       : num [1:1000000] 5.88 4.82 4 3.55 3.38 ...
  ..$ Uz       : num [1:1000000] 0.125 0.355 0.808 2.305 1.79 ...
  ..$ co2      : num [1:1000000] 859 861 862 859 860 ...
  ..$ h2o      : num [1:1000000] 8.43 8.52 8.55 8.53 8.51 ...
  ..$ Ts       : num [1:1000000] 18.8 18.6 18.4 18.7 18.6 ...
  ..$ press    : num [1:1000000] 96.6 96.6 96.6 96.6 96.7 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 1 1 1 1 1 2 1 2 2 2 ...
  ..$ diag_irga: int [1:1000000] 0 0 0 0 0 0 0 0 0 0 ...
 $ 21:'data.frame':	1000000 obs. of  11 variables:
  ..$ TIMESTAMP: Factor w/ 28487296 levels "2014-12-22 11:34:40.5",..: 21000001 21000002 21000003 21000004 21000005 21000006 21000007 21000008 21000009 21000010 ...
  ..$ RECORD   : int [1:1000000] 21000000 21000001 21000002 21000003 21000004 21000005 21000006 21000007 21000008 21000009 ...
  ..$ Ux       : num [1:1000000] 2.96 2.97 2.9 2.98 3.05 ...
  ..$ Uy       : num [1:1000000] 1.97 2.13 1.95 2.34 2.37 ...
  ..$ Uz       : num [1:1000000] -0.322 -0.273 -0.401 -0.436 -0.349 ...
  ..$ co2      : num [1:1000000] 930 931 931 931 932 ...
  ..$ h2o      : num [1:1000000] 9.58 9.59 9.6 9.56 9.55 ...
  ..$ Ts       : num [1:1000000] 11.6 11.9 12.1 12.2 12.1 ...
  ..$ press    : num [1:1000000] 97 97 97 97 97 ...
  ..$ diag_csat: Factor w/ 18 levels "0","1","10","11",..: 9 9 9 9 1 1 1 1 1 1 ...

In [12]:
for (n in seq_along(data_split)) {
  write.table(
    data_split[[n]],
    paste(
      "data/CSV/TOA5_1541.", "ts_data.", sprintf("%02d", n), ".csv", sep = ""
    ),
    row.names = FALSE, sep = ",", quote = FALSE
  )
}

## TOA5_3989.ts_data.dat

Split TOA5 file (~5.6 mil rows, ~500 MB) into max. 1 mil row files

In [22]:
system("sed -n '1,7p' 'data/TOA5/TOA5_3989.ts_data.dat'", intern = TRUE)

[1] "\"TOA5\",\"3989\",\"CR1000\",\"3989\",\"CR1000.Std.08\",\"CPU:kerry.co2.2.0.cr1\",\"33162\",\"ts_data\"\r"
[2] "\"TIMESTAMP\",\"RECORD\",\"Ux\",\"Uy\",\"Uz\",\"Ts\",\"co2\",\"h2o\",\"press\"\r"
[3] "\"TS\",\"RN\",\"m/s\",\"m/s\",\"m/s\",\"C\",\"mg/m^3\",\"g/m^3\",\"kPa\"\r"
[4] "\"\",\"\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\"\r"
[5] "\"2014-11-19 12:01:08.1\",527133419,-1.03475,3.51025,-0.03675,16.12335,602.0576,8.069658,99.81107\r"
[6] "\"2014-11-19 12:01:08.2\",527133420,-1.18775,3.2405,0.1125,16.17084,601.5311,8.136931,99.83704\r"
[7] "\"2014-11-19 12:01:08.3\",527133421,-1.3305,3.3055,0.04375,16.12335,600.9059,8.225385,99.81107\r"

In [13]:
data <- read.csv("data/TOA5/TOA5_3989.ts_data.dat", skip = 4, header = FALSE)

In [14]:
headers <- read.csv(
  "data/TOA5/TOA5_3989.ts_data.dat", skip = 1, header = FALSE, nrows = 3
)

In [15]:
headers

  V1        V2     V3  V4  V5  V6  V7     V8    V9
1 TIMESTAMP RECORD Ux  Uy  Uz  Ts  co2    h2o   press
2 TS        RN     m/s m/s m/s C   mg/m^3 g/m^3 kPa
3                  Smp Smp Smp Smp Smp    Smp   Smp

In [16]:
write.table(
  headers, "data/CSV/TOA5_3989.ts_data.headers.csv", row.names = FALSE,
  col.names = FALSE, sep = ",", quote = FALSE
)

In [17]:
names(data) <- as.matrix(
  read.csv(
    "data/TOA5/TOA5_3989.ts_data.dat", skip = 1, header = FALSE, nrows = 1
  )
)

In [18]:
head(data)

  TIMESTAMP             RECORD    Ux       Uy      Uz         Ts       co2
1 2014-11-19 12:01:08.1 527133419 -1.03475 3.51025 -0.0367500 16.12335 602.0576
2 2014-11-19 12:01:08.2 527133420 -1.18775 3.24050  0.1125000 16.17084 601.5311
3 2014-11-19 12:01:08.3 527133421 -1.33050 3.30550  0.0437500 16.12335 600.9059
4 2014-11-19 12:01:08.4 527133422 -1.55750 4.13675  0.1015000 16.20645 600.8302
5 2014-11-19 12:01:08.5 527133423 -2.05025 4.57125  0.4515000 16.15726 601.2501
6 2014-11-19 12:01:08.6 527133424 -2.28800 4.96575  0.5700001 16.35754 601.7148
  h2o      press
1 8.069658 99.81107
2 8.136931 99.83704
3 8.225385 99.81107
4 8.259484 99.78508
5 8.192789 99.83037
6 8.093515 99.77545

In [19]:
summary(data)

                 TIMESTAMP           RECORD                Ux
 2014-11-19 12:01:08.1:      1   Min.   :527133419   Min.   :-65.53
 2014-11-19 12:01:08.2:      1   1st Qu.:528551702   1st Qu.: -0.92
 2014-11-19 12:01:08.3:      1   Median :529969986   Median :  0.34
 2014-11-19 12:01:08.4:      1   Mean   :529969986   Mean   :  0.09
 2014-11-19 12:01:08.5:      1   3rd Qu.:531388270   3rd Qu.:  1.28
 2014-11-19 12:01:08.6:      1   Max.   :532806553   Max.   : 65.53
 (Other)              :5673129                       NA's   :182988
       Uy               Uz               Ts              co2
 Min.   :-65.53   Min.   :-48.29   Min.   :-38.26   Min.   : -640.9
 1st Qu.:  0.16   1st Qu.: -0.18   1st Qu.: 11.34   1st Qu.:  619.1
 Median :  1.16   Median : -0.04   Median : 14.08   Median :  632.9
 Mean   :  1.36   Mean   : -0.02   Mean   : 14.65   Mean   :  823.5
 3rd Qu.:  2.86   3rd Qu.:  0.09   3rd Qu.: 16.37   3rd Qu.:  852.2
 Max.   : 65.53   Max.   : 56.75   Max.   : 72.63   Max.   :47962.2
 NA's   :182988   NA's   :182988   NA's   :182988
      h2o              press
 Min.   : -4.280   Min.   : 97.76
 1st Qu.:  2.561   1st Qu.: 99.96
 Median :  6.267   Median :100.66
 Mean   : 23.175   Mean   :100.39
 3rd Qu.:  7.825   3rd Qu.:100.95
 Max.   :562.578   Max.   :101.93

In [20]:
nrow(data)

[1] 5673135

In [21]:
data_split <- split(data, (as.numeric(rownames(data)) - 1) %/% 1000000)

In [22]:
str(data_split)

List of 6
 $ 0:'data.frame':	1000000 obs. of  9 variables:
  ..$ TIMESTAMP: Factor w/ 5673135 levels "2014-11-19 12:01:08.1",..: 1 2 3 4 5 6 7 8 9 10 ...
  ..$ RECORD   : int [1:1000000] 527133419 527133420 527133421 527133422 527133423 527133424 527133425 527133426 527133427 527133428 ...
  ..$ Ux       : num [1:1000000] -1.03 -1.19 -1.33 -1.56 -2.05 ...
  ..$ Uy       : num [1:1000000] 3.51 3.24 3.31 4.14 4.57 ...
  ..$ Uz       : num [1:1000000] -0.0367 0.1125 0.0437 0.1015 0.4515 ...
  ..$ Ts       : num [1:1000000] 16.1 16.2 16.1 16.2 16.2 ...
  ..$ co2      : num [1:1000000] 602 602 601 601 601 ...
  ..$ h2o      : num [1:1000000] 8.07 8.14 8.23 8.26 8.19 ...
  ..$ press    : num [1:1000000] 99.8 99.8 99.8 99.8 99.8 ...
 $ 1:'data.frame':	1000000 obs. of  9 variables:
  ..$ TIMESTAMP: Factor w/ 5673135 levels "2014-11-19 12:01:08.1",..: 1000001 1000002 1000003 1000004 1000005 1000006 1000007 1000008 1000009 1000010 ...
  ..$ RECORD   : int [1:1000000] 528133419 528133420 528133421 528133422 528133423 528133424 528133425 528133426 528133427 528133428 ...
  ..$ Ux       : num [1:1000000] 0.88 0.861 0.756 0.783 0.869 ...
  ..$ Uy       : num [1:1000000] -0.448 -0.368 -0.442 -0.525 -0.475 ...
  ..$ Uz       : num [1:1000000] 0.22 0.237 0.203 0.148 0.171 ...
  ..$ Ts       : num [1:1000000] 14.4 14.4 14.4 14.4 14.5 ...
  ..$ co2      : num [1:1000000] 613 613 613 613 613 ...
  ..$ h2o      : num [1:1000000] 7.04 7.04 7.04 7.04 7.04 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
 $ 2:'data.frame':	1000000 obs. of  9 variables:
  ..$ TIMESTAMP: Factor w/ 5673135 levels "2014-11-19 12:01:08.1",..: 2000001 2000002 2000003 2000004 2000005 2000006 2000007 2000008 2000009 2000010 ...
  ..$ RECORD   : int [1:1000000] 529133419 529133420 529133421 529133422 529133423 529133424 529133425 529133426 529133427 529133428 ...
  ..$ Ux       : num [1:1000000] 2.39 3.85 4.04 4.04 3.89 ...
  ..$ Uy       : num [1:1000000] 5.05 5.12 4.41 4.01 3.92 ...
  ..$ Uz       : num [1:1000000] 0.619 0.539 0.309 0.135 0.378 ...
  ..$ Ts       : num [1:1000000] 16.3 16.2 16.1 16.1 16.1 ...
  ..$ co2      : num [1:1000000] 750 751 749 750 752 ...
  ..$ h2o      : num [1:1000000] 3.33 3.4 3.4 3.41 3.43 ...
  ..$ press    : num [1:1000000] 98.9 98.9 98.9 98.9 98.9 ...
 $ 3:'data.frame':	1000000 obs. of  9 variables:
  ..$ TIMESTAMP: Factor w/ 5673135 levels "2014-11-19 12:01:08.1",..: 3000001 3000002 3000003 3000004 3000005 3000006 3000007 3000008 3000009 3000010 ...
  ..$ RECORD   : int [1:1000000] 530133419 530133420 530133421 530133422 530133423 530133424 530133425 530133426 530133427 530133428 ...
  ..$ Ux       : num [1:1000000] 0.392 0.369 0.326 0.36 0.43 ...
  ..$ Uy       : num [1:1000000] 0.391 0.369 0.389 0.38 0.304 ...
  ..$ Uz       : num [1:1000000] -0.215 -0.18 -0.2062 -0.1225 -0.0673 ...
  ..$ Ts       : num [1:1000000] 8.37 8.34 8.35 8.32 8.29 ...
  ..$ co2      : num [1:1000000] 641 641 641 641 641 ...
  ..$ h2o      : num [1:1000000] 6 6 5.99 6 5.99 ...
  ..$ press    : num [1:1000000] 99.7 99.7 99.7 99.7 99.7 ...
 $ 4:'data.frame':	1000000 obs. of  9 variables:
  ..$ TIMESTAMP: Factor w/ 5673135 levels "2014-11-19 12:01:08.1",..: 4000001 4000002 4000003 4000004 4000005 4000006 4000007 4000008 4000009 4000010 ...
  ..$ RECORD   : int [1:1000000] 531133419 531133420 531133421 531133422 531133423 531133424 531133425 531133426 531133427 531133428 ...
  ..$ Ux       : num [1:1000000] 3.42 2.97 3.12 3.98 3.68 ...
  ..$ Uy       : num [1:1000000] 6.76 6.88 6.73 6.72 6.67 ...
  ..$ Uz       : num [1:1000000] -0.5835 0.08525 -0.00175 -0.003 0.233 ...
  ..$ Ts       : num [1:1000000] 13.6 13.6 13.5 13.6 13.6 ...
  ..$ co2      : num [1:1000000] 622 622 623 623 623 ...
  ..$ h2o      : num [1:1000000] 6.05 6.08 6.09 6.09 6.09 ...
  ..$ press    : num [1:1000000] 101 101 101 101 101 ...
 $ 5:'data.frame':	673135 obs. of  9 variables:
  ..$ TIMESTAMP: Factor w/ 5673135 levels "2014-11-19 12:01:08.1",..: 5000001 5000002 5000003 5000004 5000005 5000006 5000007 5000008 5000009 5000010 ...
  ..$ RECORD   : int [1:673135] 532133419 532133420 532133421 532133422 532133423 532133424 532133425 532133426 532133427 532133428 ...
  ..$ Ux       : num [1:673135] -0.163 -0.169 -0.182 -0.181 -0.182 ...
  ..$ Uy       : num [1:673135] 0.445 0.477 0.44 0.42 0.429 ...
  ..$ Uz       : num [1:673135] -0.0727 -0.0808 -0.0887 -0.0905 -0.0928 ...
  ..$ Ts       : num [1:673135] 17 17 17.1 17 17.1 ...
  ..$ co2      : num [1:673135] 707 706 706 705 705 ...
  ..$ h2o      : num [1:673135] 0.794 0.796 0.797 0.799 0.803 ...
  ..$ press    : num [1:673135] 101 101 101 101 101 ...

In [23]:
for (n in seq_along(data_split)) {
  write.table(
    data_split[[n]],
    paste(
      "data/CSV/TOA5_3989.", "ts_data.", sprintf("%02d", n), ".csv", sep = ""
    ),
    row.names = FALSE, sep = ",", quote = FALSE
  )
}

## TOA5_3989.flux.dat

In [47]:
system("sed -n '1,7p' 'data/TOA5/TOA5_3989.flux.dat'", intern = TRUE)

[1] "\"TOA5\",\"3989\",\"CR1000\",\"3989\",\"CR1000.Std.08\",\"CPU:kerry.co2.2.0.cr1\",\"33162\",\"flux\"\r"
[2] "\"TIMESTAMP\",\"RECORD\",\"Fc_wpl\",\"LE_wpl\",\"Hs\",\"Hc\",\"tau\",\"u_star\",\"stdev_Ts\",\"cov_Ts_Ux\",\"cov_Ts_Uy\",\"cov_Ts_Uz\",\"stdev_Ux\",\"cov_Ux_Uy\",\"cov_Ux_Uz\",\"stdev_Uy\",\"cov_Uy_Uz\",\"stdev_Uz\",\"stdev_co2\",\"cov_co2_Ux\",\"cov_co2_Uy\",\"cov_co2_Uz\",\"stdev_h2o\",\"cov_h2o_Ux\",\"cov_h2o_Uy\",\"cov_h2o_Uz\",\"Ts_mean\",\"Ux_Avg\",\"Uy_Avg\",\"Uz_Avg\",\"co2_mean\",\"h2o_Avg\",\"rho_a_mean\",\"press_mean\",\"panel_temp_Avg\",\"wind_dir\",\"rslt_wnd_spd\",\"std_wnd_dir\",\"batt_volt_Avg\",\"irga_warnings\",\"chopper_f_Tot\",\"detector_f_Tot\",\"pll_f_Tot\",\"sync_f_Tot\",\"agc_Avg\",\"Fc_irga\",\"LE_irga\",\"co2_wpl_LE\",\"co2_wpl_H\",\"h2o_wpl_LE\",\"h2o_wpl_H\",\"h2o_hmp_mean\",\"t_hmp_mean\",\"rh_hmp_mean\"\r"
[3] "\"TS\",\"RN\",\"mg/(m^2 s)\",\"W/m^2\",\"W/m^2\",\"W/m^2\",\"kg/(m s^2)\",\"m/s\",\"C\",\"m C/s\",\"m C/s\",\"m C/s\",\"m/s\",\"(m/s)^2\",\"(m/s)^2\",\"m/s\",\"(m/s)^2\",\"m/s\",\"mg/m^3\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"g/m^3\",\"g/(m^2 s)\",\"g/(m^2 s)\",\"g/(m^2 s)\",\"C\",\"m/s\",\"m/s\",\"m/s\",\"mg/m^3\",\"g/m^3\",\"kg/m^3\",\"kPa\",\"C\",\"degrees\",\"m/s\",\"degrees\",\"V\",\"samples\",\"samples\",\"samples\",\"samples\",\"samples\",\"unitless\",\"mg/(m^2 s)\",\"W/m^2\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"W/m^2\",\"W/m^2\",\"g/m^3\",\"C\",\"percent\"\r"
[4] "\"\",\"\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Avg\",\"Avg\",\"Avg\",\"Smp\",\"Avg\",\"Smp\",\"Smp\",\"Avg\",\"Smp\",\"Smp\",\"Smp\",\"Avg\",\"Tot\",\"Tot\",\"Tot\",\"Tot\",\"Tot\",\"Avg\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\"\r"
[5] "\"2014-11-19 12:30:00\",29287,-0.02738776,41.11178,27.61276,24.76925,0.2095944,0.4146389,0.3397227,-0.01496416,-0.1669969,0.02254482,1.129708,0.01969266,0.0398798,1.215521,-0.1672362,0.4648904,1.421534,-0.08834183,0.5933571,-0.08351655,0.1443758,0.04946187,-0.07262927,0.01604872,15.86149,-1.070578,4.829395,-0.0512819,602.3029,8.133391,1.219101,99.81187,11.62588,102.4991,4.946632,12.74537,12.35718,0,0,0,0,0,56,-0.08351655,39.15887,0.01285764,0.04327115,0.410987,1.541922,7.890273,11.29643,77.49195\r"
[6] "\"2014-11-19 13:00:00\",29288,-0.03498442,46.15891,28.56569,25.41201,0.1617521,0.3645584,0.255728,0.008030742,-0.09918141,0.02336177,1.19633,-0.05240786,0.05489367,1.175235,-0.1210366,0.4286742,1.054063,-0.09726954,0.5639542,-0.09378111,0.1674606,0.04367864,-0.09218977,0.01806351,16.32451,-1.174527,4.034345,-0.03606286,601.3304,8.199872,1.21707,99.831,12.30342,106.232,4.201839,15.2234,12.04245,0,0,0,0,0,56,-0.09378111,44.07496,0.01447388,0.04432281,0.4691145,1.614831,7.987618,11.80993,75.96396\r"
[7] "\"2014-11-19 13:30:00\",29289,0.1808234,-6.167122,-24.50253,-23.7634,0.1895548,0.3944006,0.8363222,-1.465492,0.3509563,-0.02001372,2.243977,-0.4614682,0.04906218,1.239739,-0.1476119,0.4406865,12.5852,14.28135,-1.820175,0.2240997,0.5437512,-0.7098227,0.1237881,-0.001944606,16.03572,0.1715313,3.838373,-0.03403701,605.4674,8.077815,1.218596,99.87163,12.67262,87.44122,3.842193,29.77846,12.06097,0,0,0,0,0,56,0.2240997,-4.744839,-0.00156682,-0.04170947,-0.04999511,-1.372288,7.917885,11.58026,76.34363\r"

In [48]:
data <- read.csv("data/TOA5/TOA5_3989.flux.dat", skip = 4, header = FALSE)

In [49]:
headers <- read.csv(
  "data/TOA5/TOA5_3989.flux.dat", skip = 1, header = FALSE, nrows = 3
)

In [50]:
headers

  V1        V2     V3         V4     V5    V6    V7         V8     V9
1 TIMESTAMP RECORD Fc_wpl     LE_wpl Hs    Hc    tau        u_star stdev_Ts
2 TS        RN     mg/(m^2 s) W/m^2  W/m^2 W/m^2 kg/(m s^2) m/s    C
3                  Smp        Smp    Smp   Smp   Smp        Smp    Smp
  V10       ⋯ V45      V46        V47     V48        V49        V50
1 cov_Ts_Ux ⋯ agc_Avg  Fc_irga    LE_irga co2_wpl_LE co2_wpl_H  h2o_wpl_LE
2 m C/s     ⋯ unitless mg/(m^2 s) W/m^2   mg/(m^2 s) mg/(m^2 s) W/m^2
3 Smp       ⋯ Avg      Smp        Smp     Smp        Smp        Smp
  V51       V52          V53        V54
1 h2o_wpl_H h2o_hmp_mean t_hmp_mean rh_hmp_mean
2 W/m^2     g/m^3        C          percent
3 Smp       Smp          Smp        Smp

In [51]:
write.table(
  headers, "data/CSV/TOA5_3989.flux.headers.csv", row.names = FALSE,
  col.names = FALSE, sep = ",", quote = FALSE
)

In [52]:
names(data) <- as.matrix(
  read.csv("data/TOA5/TOA5_3989.flux.dat", skip = 1, header = FALSE, nrows = 1)
)

In [53]:
head(data)

  TIMESTAMP           RECORD Fc_wpl      LE_wpl     Hs         Hc
1 2014-11-19 12:30:00 29287  -0.02738776  41.111780  27.612760  24.769250
2 2014-11-19 13:00:00 29288  -0.03498442  46.158910  28.565690  25.412010
3 2014-11-19 13:30:00 29289   0.18082340  -6.167122 -24.502530 -23.763400
4 2014-11-19 14:00:00 29290   2.18144700 -36.546420  -8.166809  -5.908159
5 2014-11-19 14:30:00 29291  -0.07790546  37.358010  -5.191130  -7.278997
6 2014-11-19 15:00:00 29292  -0.01854837  29.914260 -19.607910 -21.032380
  tau        u_star    stdev_Ts  cov_Ts_Ux    ⋯ agc_Avg  Fc_irga
1 0.20959440 0.4146389 0.3397227 -0.014964160 ⋯ 56.00000 -0.083516550
2 0.16175210 0.3645584 0.2557280  0.008030742 ⋯ 56.00000 -0.093781110
3 0.18955480 0.3944006 0.8363222 -1.465492000 ⋯ 56.00000  0.224099700
4 0.07494499 0.2468190 0.8353181 -0.894337100 ⋯ 59.64111  2.224159000
5 0.03453151 0.1677954 0.3394781 -0.030340910 ⋯ 56.00000 -0.077377380
6 0.08993658 0.2712201 0.2265035 -0.108646600 ⋯ 56.00000  0.008064821
  LE_irga    co2_wpl_LE  co2_wpl_H   h2o_wpl_LE  h2o_wpl_H  h2o_hmp_mean
1  39.158870  0.01285764  0.04327115  0.41098700  1.5419220 7.890273
2  44.074960  0.01447388  0.04432281  0.46911450  1.6148310 7.987618
3  -4.744839 -0.00156682 -0.04170947 -0.04999511 -1.3722880 7.917885
4 -35.732150 -0.02265313 -0.02005932 -0.36612430 -0.4481432 7.774566
5  37.254240  0.01248777 -0.01301585  0.40426460 -0.3004996 8.205495
6  30.713200  0.01006716 -0.03668035  0.33333760 -1.1322800 8.181075
  t_hmp_mean rh_hmp_mean
1 11.296430  77.49195
2 11.809930  75.96396
3 11.580260  76.34363
4  9.416086  85.95309
5 10.590230  84.24697
6 11.328960  80.18222

In [54]:
summary(data)

  TIMESTAMP             RECORD          Fc_wpl              LE_wpl
 Length:315         Min.   :29287   Min.   :-30.77266   Min.   :-989.053
 Class :character   1st Qu.:29366   1st Qu.: -0.03088   1st Qu.:  -2.588
 Mode  :character   Median :29444   Median :  0.00539   Median :   4.270
                    Mean   :29444   Mean   :  0.42724   Mean   :  40.929
                    3rd Qu.:29522   3rd Qu.:  0.04355   3rd Qu.:  25.208
                    Max.   :29601   Max.   : 44.67786   Max.   :3450.499
                                    NA's   :33          NA's   :33
       Hs                Hc                tau              u_star
 Min.   :-293.11   Min.   :-281.913   Min.   :0.00014   Min.   :0.01061
 1st Qu.: -31.69   1st Qu.: -33.786   1st Qu.:0.01121   1st Qu.:0.09429
 Median : -16.97   Median : -17.278   Median :0.05655   Median :0.21326
 Mean   : -19.75   Mean   : -21.704   Mean   :0.12857   Mean   :0.25505
 3rd Qu.:  -3.43   3rd Qu.:  -3.731   3rd Qu.:0.14201   3rd Qu.:0.34064
 Max.   :  69.14   Max.   :  64.217   Max.   :2.25426   Max.   :1.35856
 NA's   :33        NA's   :33         NA's   :33        NA's   :33
    stdev_Ts         cov_Ts_Ux          cov_Ts_Uy          cov_Ts_Uz
 Min.   :0.03464   Min.   :-1.46549   Min.   :-1.56476   Min.   :-0.23887
 1st Qu.:0.23219   1st Qu.:-0.08778   1st Qu.:-0.02577   1st Qu.:-0.02592
 Median :0.34047   Median :-0.00392   Median : 0.04520   Median :-0.01350
 Mean   :0.48979   Mean   :-0.01952   Mean   : 0.03803   Mean   :-0.01599
 3rd Qu.:0.68703   3rd Qu.: 0.06147   3rd Qu.: 0.13758   3rd Qu.:-0.00275
 Max.   :1.78375   Max.   : 0.86680   Max.   : 0.97588   Max.   : 0.05549
 NA's   :33        NA's   :33         NA's   :33         NA's   :33
    stdev_Ux        cov_Ux_Uy          cov_Ux_Uz           stdev_Uy
 Min.   :0.1456   Min.   :-3.58132   Min.   :-0.14344   Min.   :0.2158
 1st Qu.:0.4803   1st Qu.:-0.18371   1st Qu.:-0.02054   1st Qu.:0.5514
 Median :0.7388   Median :-0.03746   Median : 0.00086   Median :0.8111
 Mean   :0.8451   Mean   :-0.12549   Mean   : 0.03834   Mean   :0.9162
 3rd Qu.:1.0150   3rd Qu.: 0.06900   3rd Qu.: 0.01349   3rd Qu.:1.0846
 Max.   :2.9566   Max.   : 0.94370   Max.   : 1.20227   Max.   :2.9743
 NA's   :33       NA's   :33         NA's   :33         NA's   :33
   cov_Uy_Uz           stdev_Uz        stdev_co2           cov_co2_Ux
 Min.   :-1.49308   Min.   :0.0286   Min.   :   0.3626   Min.   :-196.4054
 1st Qu.:-0.07865   1st Qu.:0.1142   1st Qu.:   1.6009   1st Qu.:  -0.3046
 Median :-0.01709   Median :0.2716   Median :   6.7513   Median :   0.1558
 Mean   :-0.05822   Mean   :0.2860   Mean   : 149.0408   Mean   :  25.5833
 3rd Qu.:-0.00456   3rd Qu.:0.3876   3rd Qu.: 186.9009   3rd Qu.:   2.0578
 Max.   : 0.10252   Max.   :1.0109   Max.   :2375.0930   Max.   :1751.2470
 NA's   :33         NA's   :33                           NA's   :33
   cov_co2_Uy          cov_co2_Uz          stdev_h2o
 Min.   :-415.0829   Min.   :-30.22648   Min.   :  0.02117
 1st Qu.:  -1.1935   1st Qu.: -0.03577   1st Qu.:  0.10828
 Median :  -0.1664   Median :  0.04498   Median :  0.25594
 Mean   :   3.5193   Mean   :  0.47365   Mean   :  4.01431
 3rd Qu.:   0.6810   3rd Qu.:  0.09548   3rd Qu.:  2.86492
 Max.   : 848.4179   Max.   : 45.99002   Max.   :126.36140
 NA's   :33          NA's   :33
   cov_h2o_Ux          cov_h2o_Uy          cov_h2o_Uz          Ts_mean
 Min.   :-18.98351   Min.   :-31.31385   Min.   :-0.40175   Min.   : 5.32
 1st Qu.: -0.06995   1st Qu.: -0.05945   1st Qu.:-0.00071   1st Qu.:11.13
 Median : -0.00642   Median : -0.00760   Median : 0.00215   Median :13.75
 Mean   : -0.17526   Mean   :  0.07990   Mean   : 0.01707   Mean   :13.41
 3rd Qu.:  0.02401   3rd Qu.:  0.02780   3rd Qu.: 0.01088   3rd Qu.:16.00
 Max.   : 14.98236   Max.   : 15.52319   Max.   : 1.40207   Max.   :23.50
 NA's   :33          NA's   :33          NA's   :33         NA's   :33
     Ux_Avg            Uy_Avg           Uz_Avg            co2_mean
 Min.   :-6.7677   Min.   :-2.202   Min.   :-0.15439   Min.   :-224.4
 1st Qu.:-0.6089   1st Qu.: 0.295   1st Qu.:-0.05778   1st Qu.: 620.6
 Median : 0.4334   Median : 1.129   Median :-0.04281   Median : 640.2
 Mean   : 0.1054   Mean   : 1.581   Mean   :-0.04271   Mean   : 823.6
 3rd Qu.: 1.0829   3rd Qu.: 2.893   3rd Qu.:-0.02909   3rd Qu.: 903.2
 Max.   : 4.9367   Max.   : 6.411   Max.   : 0.06825   Max.   :2533.1
 NA's   :33        NA's   :33       NA's   :33
    h2o_Avg          rho_a_mean      press_mean     panel_temp_Avg
 Min.   : -3.061   Min.   :1.196   Min.   : 97.87   Min.   : 0.6046
 1st Qu.:  2.672   1st Qu.:1.226   1st Qu.: 99.96   1st Qu.: 6.6876
 Median :  6.163   Median :1.241   Median :100.66   Median : 9.2555
 Mean   : 23.180   Mean   :1.239   Mean   :100.39   Mean   : 8.4092
 3rd Qu.:  7.533   3rd Qu.:1.253   3rd Qu.:100.95   3rd Qu.:10.6339
 Max.   :491.951   Max.   :1.279   Max.   :101.82   Max.   :13.8082

    wind_dir        rslt_wnd_spd     std_wnd_dir    batt_volt_Avg
 Min.   :-176.90   Min.   :0.1065   Min.   : 0.00   Min.   : 8.915
 1st Qu.:   0.00   1st Qu.:1.1367   1st Qu.:11.33   1st Qu.:10.948
 Median :  54.68   Median :2.6130   Median :16.46   Median :11.372
 Mean   :  48.70   Mean   :2.6214   Mean   :20.62   Mean   :11.265
 3rd Qu.:  93.77   3rd Qu.:3.8503   3rd Qu.:28.33   3rd Qu.:11.683
 Max.   : 179.18   Max.   :8.4682   Max.   :75.46   Max.   :12.357
                   NA's   :33
 irga_warnings      chopper_f_Tot      detector_f_Tot   pll_f_Tot   sync_f_Tot
 Min.   :  0.0000   Min.   :  0.0000   Min.   :0      Min.   :0   Min.   :0
 1st Qu.:  0.0000   1st Qu.:  0.0000   1st Qu.:0      1st Qu.:0   1st Qu.:0
 Median :  0.0000   Median :  0.0000   Median :0      Median :0   Median :0
 Mean   :  0.5873   Mean   :  0.5873   Mean   :0      Mean   :0   Mean   :0
 3rd Qu.:  0.0000   3rd Qu.:  0.0000   3rd Qu.:0      3rd Qu.:0   3rd Qu.:0
 Max.   :185.0000   Max.   :185.0000   Max.   :0      Max.   :0   Max.   :0

    agc_Avg         Fc_irga             LE_irga           co2_wpl_LE
 Min.   :50.00   Min.   :-30.22648   Min.   :-980.277   Min.   :-0.64364
 1st Qu.:56.00   1st Qu.: -0.03577   1st Qu.:  -1.733   1st Qu.:-0.00073
 Median :56.00   Median :  0.04498   Median :   5.258   Median : 0.00170
 Mean   :64.00   Mean   :  0.47365   Mean   :  41.652   Mean   : 0.00767
 3rd Qu.:71.28   3rd Qu.:  0.09548   3rd Qu.:  26.546   3rd Qu.: 0.00917
 Max.   :94.00   Max.   : 45.99002   Max.   :3421.049   Max.   : 0.64875
                 NA's   :33          NA's   :33         NA's   :33
   co2_wpl_H          h2o_wpl_LE         h2o_wpl_H         h2o_hmp_mean
 Min.   :-1.29340   Min.   :-7.88571   Min.   :-17.8013   Min.   : 4.716
 1st Qu.:-0.06832   1st Qu.:-0.01425   1st Qu.: -1.7625   1st Qu.: 6.315
 Median :-0.03378   Median : 0.05449   Median : -0.8614   Median : 7.487
 Mean   :-0.05408   Mean   : 0.36380   Mean   : -1.0862   Mean   : 7.329
 3rd Qu.:-0.00581   3rd Qu.: 0.27048   3rd Qu.: -0.1662   3rd Qu.: 8.320
 Max.   : 0.34564   Max.   :29.29822   Max.   :  4.2145   Max.   :10.740
 NA's   :33         NA's   :33         NA's   :33
   t_hmp_mean       rh_hmp_mean
 Min.   : 0.9912   Min.   :66.27
 1st Qu.: 6.9690   1st Qu.:80.63
 Median : 8.8031   Median :86.16
 Mean   : 8.3998   Mean   :85.67
 3rd Qu.:10.3732   3rd Qu.:92.74
 Max.   :13.5707   Max.   :97.27

In [55]:
nrow(data)

[1] 315

In [56]:
write.table(
  headers, "data/CSV/TOA5_3989.flux.csv", row.names = FALSE,
  sep = ",", quote = FALSE
)

## TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2015).dat

In [36]:
system(
  "sed -n '1,7p' 'data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2015).dat'",
  intern = TRUE
)

[1] "\"TOA5\",\"3989\",\"CR1000\",\"3989\",\"CR1000.Std.08\",\"CPU:kerry.co2.2.0.cr1\",\"33162\",\"flux\"\r"
[2] "\"TIMESTAMP\",\"RECORD\",\"Fc_wpl\",\"LE_wpl\",\"Hs\",\"Hc\",\"tau\",\"u_star\",\"stdev_Ts\",\"cov_Ts_Ux\",\"cov_Ts_Uy\",\"cov_Ts_Uz\",\"stdev_Ux\",\"cov_Ux_Uy\",\"cov_Ux_Uz\",\"stdev_Uy\",\"cov_Uy_Uz\",\"stdev_Uz\",\"stdev_co2\",\"cov_co2_Ux\",\"cov_co2_Uy\",\"cov_co2_Uz\",\"stdev_h2o\",\"cov_h2o_Ux\",\"cov_h2o_Uy\",\"cov_h2o_Uz\",\"Ts_mean\",\"Ux_Avg\",\"Uy_Avg\",\"Uz_Avg\",\"co2_mean\",\"h2o_Avg\",\"rho_a_mean\",\"press_mean\",\"panel_temp_Avg\",\"wind_dir\",\"rslt_wnd_spd\",\"std_wnd_dir\",\"batt_volt_Avg\",\"irga_warnings\",\"chopper_f_Tot\",\"detector_f_Tot\",\"pll_f_Tot\",\"sync_f_Tot\",\"agc_Avg\",\"Fc_irga\",\"LE_irga\",\"co2_wpl_LE\",\"co2_wpl_H\",\"h2o_wpl_LE\",\"h2o_wpl_H\",\"h2o_hmp_mean\",\"t_hmp_mean\",\"rh_hmp_mean\"\r"
[3] "\"TS\",\"RN\",\"mg/(m^2 s)\",\"W/m^2\",\"W/m^2\",\"W/m^2\",\"kg/(m s^2)\",\"m/s\",\"C\",\"m C/s\",\"m C/s\",\"m C/s\",\"m/s\",\"(m/s)^2\",\"(m/s)^2\",\"m/s\",\"(m/s)^2\",\"m/s\",\"mg/m^3\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"g/m^3\",\"g/(m^2 s)\",\"g/(m^2 s)\",\"g/(m^2 s)\",\"C\",\"m/s\",\"m/s\",\"m/s\",\"mg/m^3\",\"g/m^3\",\"kg/m^3\",\"kPa\",\"C\",\"degrees\",\"m/s\",\"degrees\",\"V\",\"samples\",\"samples\",\"samples\",\"samples\",\"samples\",\"unitless\",\"mg/(m^2 s)\",\"W/m^2\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"W/m^2\",\"W/m^2\",\"g/m^3\",\"C\",\"percent\"\r"
[4] "\"\",\"\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Avg\",\"Avg\",\"Avg\",\"Smp\",\"Avg\",\"Smp\",\"Smp\",\"Avg\",\"Smp\",\"Smp\",\"Smp\",\"Avg\",\"Tot\",\"Tot\",\"Tot\",\"Tot\",\"Tot\",\"Avg\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\"\r"
[5] "\"2015-04-16 10:30:00\",33528,-0.07050741,75.43386,139.7478,133.3558,0.01570627,0.1136141,0.7702006,0.0287227,0.03381336,0.1143175,0.7624483,0.2069015,0.01236219,0.9078643,-0.00371439,0.2849423,2.405463,-0.2433473,-0.1619354,-0.3332449,0.2030236,0.01568299,0.01604299,0.02766319,17.15509,-0.9320452,-1.126813,0.02570675,623.1078,6.780926,1.216771,100.2397,14.18789,-129.5959,1.462332,28.70714,13.23716,0,0,0,0,0,56,-0.3332449,67.49818,0.02296296,0.2397746,0.6645014,7.271169,7.389947,13.13227,64.73261\r"
[6] "\"2015-04-16 11:00:00\",33529,-0.06113067,97.84227,183.5227,175.0836,0.006824024,0.07498017,0.8852791,0.0007770061,0.02217865,0.1504938,1.071358,0.0276407,-0.005268425,1.02806,0.001962364,0.3263579,2.514321,0.08234715,-0.1506004,-0.4046633,0.2338435,0.009415597,0.02544558,0.03581095,17.99106,-0.8767914,-1.744364,0.01492664,621.0428,6.827036,1.213802,100.2263,14.74764,-116.686,1.952328,30.07014,13.24102,0,0,0,0,0,56,-0.4046633,87.37871,0.02970162,0.313831,0.8665181,9.597045,7.42556,13.78645,62.4719\r"
[7] "\"2015-04-16 11:30:00\",33530,0.009571165,104.2355,199.8177,190.7273,0.08037375,0.257495,0.9643432,-0.291831,-0.04099387,0.1640718,1.338304,0.4940267,-0.06306306,1.163296,-0.020475,0.3454463,2.95971,0.7013156,-0.119334,-0.3658124,0.2646294,-0.005396664,-0.009120643,0.03798236,18.38503,-0.6437444,-2.393694,0.04266752,624.1392,6.951874,1.212207,100.2205,14.84076,-105.0526,2.478747,29.27938,13.2421,0,0,0,0,0,56,-0.3658124,92.67695,0.03170475,0.3436788,0.9354095,10.6231,7.546908,14.12835,62.17416\r"

In [37]:
data <- read.csv(
  "data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2015).dat",
  skip = 4, header = FALSE
)

In [38]:
headers <- read.csv(
  "data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2015).dat",
  skip = 1, header = FALSE, nrows = 3
)

In [39]:
headers

  V1        V2     V3         V4     V5    V6    V7         V8     V9
1 TIMESTAMP RECORD Fc_wpl     LE_wpl Hs    Hc    tau        u_star stdev_Ts
2 TS        RN     mg/(m^2 s) W/m^2  W/m^2 W/m^2 kg/(m s^2) m/s    C
3                  Smp        Smp    Smp   Smp   Smp        Smp    Smp
  V10       ⋯ V45      V46        V47     V48        V49        V50
1 cov_Ts_Ux ⋯ agc_Avg  Fc_irga    LE_irga co2_wpl_LE co2_wpl_H  h2o_wpl_LE
2 m C/s     ⋯ unitless mg/(m^2 s) W/m^2   mg/(m^2 s) mg/(m^2 s) W/m^2
3 Smp       ⋯ Avg      Smp        Smp     Smp        Smp        Smp
  V51       V52          V53        V54
1 h2o_wpl_H h2o_hmp_mean t_hmp_mean rh_hmp_mean
2 W/m^2     g/m^3        C          percent
3 Smp       Smp          Smp        Smp

In [40]:
write.table(
  headers, "data/CSV/TOA5_3989.2015.flux.headers.csv", row.names = FALSE,
  col.names = FALSE, sep = ",", quote = FALSE
)

In [41]:
names(data) <- as.matrix(
  read.csv(
    "data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2015).dat",
    skip = 1, header = FALSE, nrows = 1
  )
)

In [42]:
head(data)

  TIMESTAMP           RECORD Fc_wpl       LE_wpl    Hs       Hc
1 2015-04-16 10:30:00 33528  -0.070507410  75.43386 139.7478 133.3558
2 2015-04-16 11:00:00 33529  -0.061130670  97.84227 183.5227 175.0836
3 2015-04-16 11:30:00 33530   0.009571165 104.23550 199.8177 190.7273
4 2015-04-16 12:00:00 33531  -0.053656130 114.78070 169.4980 160.3188
5 2015-04-16 12:30:00 33532  -0.058696390 122.23720 205.8765 195.6567
6 2015-04-16 13:00:00 33533  -0.039852740 111.92110 187.7205 178.3878
  tau         u_star     stdev_Ts  cov_Ts_Ux     ⋯ agc_Avg Fc_irga    LE_irga
1 0.015706270 0.11361410 0.7702006  0.0287227000 ⋯ 56      -0.3332449  67.49818
2 0.006824024 0.07498017 0.8852791  0.0007770061 ⋯ 56      -0.4046633  87.37871
3 0.080373750 0.25749500 0.9643432 -0.2918310000 ⋯ 56      -0.3658124  92.67695
4 0.037065820 0.17503830 0.8076537  0.1571966000 ⋯ 56      -0.3771344 104.77400
5 0.058038200 0.21918670 0.9739804 -0.2421052000 ⋯ 56      -0.4449696 110.40930
6 0.032758150 0.16478070 0.8736999  0.0738351200 ⋯ 56      -0.3915091 101.31530
  co2_wpl_LE co2_wpl_H h2o_wpl_LE h2o_wpl_H h2o_hmp_mean t_hmp_mean rh_hmp_mean
1 0.02296296 0.2397746 0.6645014   7.271169 7.389947     13.13227   64.73261
2 0.02970162 0.3138310 0.8665181   9.597045 7.425560     13.78645   62.47190
3 0.03170475 0.3436788 0.9354095  10.623100 7.546908     14.12835   62.17416
4 0.03576480 0.2877135 1.0527530   8.953876 7.498158     14.66202   59.78199
5 0.03748565 0.3487876 1.0961310  10.731750 7.398589     15.02505   57.70282
6 0.03436560 0.3172907 0.9897227   9.615979 7.271001     15.38198   55.48570

In [43]:
summary(data)

  TIMESTAMP             RECORD          Fc_wpl              LE_wpl
 Length:1353        Min.   :33528   Min.   :-26.63347   Min.   :-1517.564
 Class :character   1st Qu.:33866   1st Qu.: -0.05101   1st Qu.:    3.198
 Mode  :character   Median :34204   Median :  0.00340   Median :   29.763
                    Mean   :34204   Mean   :  0.28041   Mean   :   44.565
                    3rd Qu.:34542   3rd Qu.:  0.04476   3rd Qu.:   79.674
                    Max.   :34880   Max.   : 37.98938   Max.   : 3423.436
                                    NA's   :25          NA's   :25
       Hs                  Hc                 tau               u_star
 Min.   :-289.0884   Min.   :-282.8151   Min.   :0.000322   Min.   :0.01613
 1st Qu.: -20.8547   1st Qu.: -20.9109   1st Qu.:0.039111   1st Qu.:0.17856
 Median :  -0.3793   Median :  -0.6386   Median :0.140703   Median :0.33886
 Mean   :  28.5935   Mean   :  25.6023   Mean   :0.202495   Mean   :0.34968
 3rd Qu.:  67.9546   3rd Qu.:  63.0869   3rd Qu.:0.270965   3rd Qu.:0.46973
 Max.   : 287.8950   Max.   : 274.2198   Max.   :1.961947   Max.   :1.27286
 NA's   :25          NA's   :25          NA's   :25         NA's   :25
    stdev_Ts         cov_Ts_Ux           cov_Ts_Uy           cov_Ts_Uz
 Min.   :0.03514   Min.   :-3.057249   Min.   :-2.379055   Min.   :-0.237813
 1st Qu.:0.20734   1st Qu.:-0.102282   1st Qu.:-0.092158   1st Qu.:-0.016936
 Median :0.37911   Median :-0.001008   Median : 0.004596   Median :-0.000303
 Mean   :0.48361   Mean   :-0.027852   Mean   :-0.017835   Mean   : 0.023412
 3rd Qu.:0.68653   3rd Qu.: 0.079594   3rd Qu.: 0.078856   3rd Qu.: 0.055477
 Max.   :2.57834   Max.   : 0.903413   Max.   : 2.559403   Max.   : 0.236086
 NA's   :25        NA's   :25          NA's   :25          NA's   :25
    stdev_Ux        cov_Ux_Uy          cov_Ux_Uz            stdev_Uy
 Min.   :0.1493   Min.   :-2.27827   Min.   :-0.459338   Min.   :0.1948
 1st Qu.:0.7244   1st Qu.:-0.13587   1st Qu.:-0.098458   1st Qu.:0.7706
 Median :1.0624   Median : 0.02751   Median :-0.004777   Median :1.0977
 Mean   :1.1015   Mean   : 0.03452   Mean   :-0.016658   Mean   :1.1579
 3rd Qu.:1.3998   3rd Qu.: 0.22553   3rd Qu.: 0.029275   3rd Qu.:1.4801
 Max.   :3.2504   Max.   : 6.46954   Max.   : 0.857133   Max.   :3.0788
 NA's   :25       NA's   :25         NA's   :25          NA's   :25
   cov_Uy_Uz            stdev_Uz         stdev_co2          cov_co2_Ux
 Min.   :-1.554610   Min.   :0.02824   Min.   :   0.176   Min.   :-754.3134
 1st Qu.:-0.107449   1st Qu.:0.24643   1st Qu.:   1.761   1st Qu.:  -0.8284
 Median :-0.024738   Median :0.39726   Median :   4.125   Median :   0.0176
 Mean   :-0.074044   Mean   :0.40512   Mean   : 107.352   Mean   :  -0.7807
 3rd Qu.: 0.000118   3rd Qu.:0.53112   3rd Qu.:  73.318   3rd Qu.:   1.0453
 Max.   : 0.899695   Max.   :1.03345   Max.   :5411.754   Max.   : 737.8526
 NA's   :25          NA's   :25                           NA's   :25
   cov_co2_Uy           cov_co2_Uz          stdev_h2o
 Min.   :-1019.4240   Min.   :-27.02823   Min.   :  0.02125
 1st Qu.:   -0.8109   1st Qu.: -0.27910   1st Qu.:  0.14743
 Median :    0.0258   Median : -0.01564   Median :  0.30028
 Mean   :   -3.5909   Mean   :  0.22280   Mean   :  1.76650
 3rd Qu.:    0.9373   3rd Qu.:  0.09397   3rd Qu.:  1.99207
 Max.   :  567.4697   Max.   : 37.66028   Max.   :181.62370
 NA's   :25           NA's   :25
   cov_h2o_Ux          cov_h2o_Uy         cov_h2o_Uz           Ts_mean
 Min.   :-67.47302   Min.   :-9.78330   Min.   :-0.616813   Min.   : 5.388
 1st Qu.: -0.08399   1st Qu.:-0.07847   1st Qu.: 0.001591   1st Qu.:12.629
 Median :  0.00236   Median :-0.00330   Median : 0.012182   Median :14.589
 Mean   : -0.14067   Mean   : 0.08234   Mean   : 0.017573   Mean   :14.721
 3rd Qu.:  0.05962   3rd Qu.: 0.05540   3rd Qu.: 0.031148   3rd Qu.:16.721
 Max.   : 21.72854   Max.   :41.97945   Max.   : 1.392476   Max.   :23.176
 NA's   :25          NA's   :25         NA's   :25          NA's   :25
     Ux_Avg            Uy_Avg            Uz_Avg             co2_mean
 Min.   :-7.5456   Min.   :-6.4546   Min.   :-0.232368   Min.   : -13.48
 1st Qu.:-1.2220   1st Qu.:-0.3579   1st Qu.:-0.053298   1st Qu.: 626.67
 Median : 0.4738   Median : 1.0124   Median :-0.034601   Median : 643.09
 Mean   : 0.9553   Mean   : 1.4631   Mean   :-0.024968   Mean   : 724.89
 3rd Qu.: 3.4752   3rd Qu.: 3.1204   3rd Qu.:-0.005206   3rd Qu.: 709.16
 Max.   : 9.5281   Max.   :11.2360   Max.   : 0.221962   Max.   :5102.09
 NA's   :25        NA's   :25        NA's   :25
    h2o_Avg          rho_a_mean      press_mean     panel_temp_Avg
 Min.   : -2.900   Min.   :1.185   Min.   : 97.40   Min.   : 0.3427
 1st Qu.:  3.634   1st Qu.:1.214   1st Qu.: 99.43   1st Qu.: 7.8563
 Median :  5.773   Median :1.227   Median :100.05   Median :10.4057
 Mean   :  7.341   Mean   :1.228   Mean   :100.01   Mean   :10.5032
 3rd Qu.:  6.791   3rd Qu.:1.241   3rd Qu.:100.67   3rd Qu.:12.8370
 Max.   :523.327   Max.   :1.288   Max.   :102.28   Max.   :20.9951

    wind_dir        rslt_wnd_spd       std_wnd_dir    batt_volt_Avg
 Min.   :-179.91   Min.   : 0.04004   Min.   : 0.00   Min.   :13.17
 1st Qu.: -32.12   1st Qu.: 1.78388   1st Qu.:11.39   1st Qu.:13.19
 Median :  43.72   Median : 3.76144   Median :15.02   Median :13.20
 Mean   :  24.67   Mean   : 4.02892   Mean   :19.92   Mean   :13.20
 3rd Qu.:  80.38   3rd Qu.: 5.57626   3rd Qu.:22.70   3rd Qu.:13.21
 Max.   : 179.85   Max.   :11.95476   Max.   :79.66   Max.   :13.25
                   NA's   :25
 irga_warnings chopper_f_Tot detector_f_Tot   pll_f_Tot   sync_f_Tot
 Min.   :0     Min.   :0     Min.   :0      Min.   :0   Min.   :0
 1st Qu.:0     1st Qu.:0     1st Qu.:0      1st Qu.:0   1st Qu.:0
 Median :0     Median :0     Median :0      Median :0   Median :0
 Mean   :0     Mean   :0     Mean   :0      Mean   :0   Mean   :0
 3rd Qu.:0     3rd Qu.:0     3rd Qu.:0      3rd Qu.:0   3rd Qu.:0
 Max.   :0     Max.   :0     Max.   :0      Max.   :0   Max.   :0

    agc_Avg         Fc_irga             LE_irga            co2_wpl_LE
 Min.   :50.00   Min.   :-27.02823   Min.   :-1505.024   Min.   :-0.794727
 1st Qu.:56.00   1st Qu.: -0.27910   1st Qu.:    3.882   1st Qu.: 0.001364
 Median :56.00   Median : -0.01564   Median :   29.724   Median : 0.010659
 Mean   :59.53   Mean   :  0.22280   Mean   :   42.878   Mean   : 0.014220
 3rd Qu.:59.60   3rd Qu.:  0.09397   3rd Qu.:   76.001   3rd Qu.: 0.026938
 Max.   :94.00   Max.   : 37.66028   Max.   : 3397.642   Max.   : 1.533475
                 NA's   :25          NA's   :25          NA's   :25
   co2_wpl_H           h2o_wpl_LE          h2o_wpl_H         h2o_hmp_mean
 Min.   :-1.381746   Min.   :-13.06556   Min.   :-21.0338   Min.   : 3.282
 1st Qu.:-0.041996   1st Qu.:  0.03127   1st Qu.: -0.9904   1st Qu.: 6.163
 Median :-0.001235   Median :  0.27419   Median : -0.0191   Median : 7.003
 Mean   : 0.043391   Mean   :  0.39001   Mean   :  1.2964   Mean   : 7.074
 3rd Qu.: 0.126153   3rd Qu.:  0.70287   3rd Qu.:  3.4311   3rd Qu.: 7.745
 Max.   : 0.483189   Max.   : 25.26338   Max.   : 16.1668   Max.   :10.348
 NA's   :25          NA's   :25          NA's   :25
   t_hmp_mean      rh_hmp_mean
 Min.   : 1.190   Min.   :21.64
 1st Qu.: 7.977   1st Qu.:67.95
 Median : 9.964   Median :79.06
 Mean   :10.008   Mean   :75.86
 3rd Qu.:11.852   3rd Qu.:87.17
 Max.   :19.006   Max.   :96.49

In [44]:
nrow(data)

[1] 1353

In [45]:
write.table(
  headers, "data/CSV/TOA5_3989.2015.flux.csv", row.names = FALSE,
  sep = ",", quote = FALSE
)

## TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2016).dat

In [57]:
system(
  "sed -n '1,7p' 'data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2016).dat'",
  intern = TRUE
)

[1] "\"TOA5\",\"3989\",\"CR1000\",\"3989\",\"CR1000.Std.08\",\"CPU:kerry.co2.2.0.cr1\",\"33162\",\"flux\"\r"
[2] "\"TIMESTAMP\",\"RECORD\",\"Fc_wpl\",\"LE_wpl\",\"Hs\",\"Hc\",\"tau\",\"u_star\",\"stdev_Ts\",\"cov_Ts_Ux\",\"cov_Ts_Uy\",\"cov_Ts_Uz\",\"stdev_Ux\",\"cov_Ux_Uy\",\"cov_Ux_Uz\",\"stdev_Uy\",\"cov_Uy_Uz\",\"stdev_Uz\",\"stdev_co2\",\"cov_co2_Ux\",\"cov_co2_Uy\",\"cov_co2_Uz\",\"stdev_h2o\",\"cov_h2o_Ux\",\"cov_h2o_Uy\",\"cov_h2o_Uz\",\"Ts_mean\",\"Ux_Avg\",\"Uy_Avg\",\"Uz_Avg\",\"co2_mean\",\"h2o_Avg\",\"rho_a_mean\",\"press_mean\",\"panel_temp_Avg\",\"wind_dir\",\"rslt_wnd_spd\",\"std_wnd_dir\",\"batt_volt_Avg\",\"irga_warnings\",\"chopper_f_Tot\",\"detector_f_Tot\",\"pll_f_Tot\",\"sync_f_Tot\",\"agc_Avg\",\"Fc_irga\",\"LE_irga\",\"co2_wpl_LE\",\"co2_wpl_H\",\"h2o_wpl_LE\",\"h2o_wpl_H\",\"h2o_hmp_mean\",\"t_hmp_mean\",\"rh_hmp_mean\"\r"
[3] "\"TS\",\"RN\",\"mg/(m^2 s)\",\"W/m^2\",\"W/m^2\",\"W/m^2\",\"kg/(m s^2)\",\"m/s\",\"C\",\"m C/s\",\"m C/s\",\"m C/s\",\"m/s\",\"(m/s)^2\",\"(m/s)^2\",\"m/s\",\"(m/s)^2\",\"m/s\",\"mg/m^3\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"g/m^3\",\"g/(m^2 s)\",\"g/(m^2 s)\",\"g/(m^2 s)\",\"C\",\"m/s\",\"m/s\",\"m/s\",\"mg/m^3\",\"g/m^3\",\"kg/m^3\",\"kPa\",\"C\",\"degrees\",\"m/s\",\"degrees\",\"V\",\"samples\",\"samples\",\"samples\",\"samples\",\"samples\",\"unitless\",\"mg/(m^2 s)\",\"W/m^2\",\"mg/(m^2 s)\",\"mg/(m^2 s)\",\"W/m^2\",\"W/m^2\",\"g/m^3\",\"C\",\"percent\"\r"
[4] "\"\",\"\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Avg\",\"Avg\",\"Avg\",\"Smp\",\"Avg\",\"Smp\",\"Smp\",\"Avg\",\"Smp\",\"Smp\",\"Smp\",\"Avg\",\"Tot\",\"Tot\",\"Tot\",\"Tot\",\"Tot\",\"Avg\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\",\"Smp\"\r"
[5] "\"2016-06-09 08:30:00\",44801,-0.1307632,37.03913,25.60763,23.3344,0.1181751,0.3133757,0.2528313,-0.01505542,-0.07113852,0.02118119,0.9986033,-0.03467703,0.004057795,1.13161,-0.09812042,0.3728273,1.872982,0.1896596,0.859367,-0.1936334,0.1459866,-0.01045346,-0.08244079,0.01417896,16.35466,-0.1112268,2.938537,-0.01629304,723.5212,9.118859,1.20336,100.2632,16.41071,92.16766,2.940639,18.63249,12.99674,0,0,0,0,0,50,-0.1936334,34.59666,0.0138582,0.04901194,0.5003809,1.942085,10.70669,15.89368,79.20306\r"
[6] "\"2016-06-09 09:00:00\",44802,-0.1701145,54.49001,62.58549,59.215,0.1070421,0.298587,0.4525773,0.008037789,-0.1740882,0.05188449,0.8466863,0.06221153,-0.01557749,0.8815346,-0.08778278,0.3223213,2.784797,0.1742953,1.233275,-0.3134294,0.1825024,-0.001951572,-0.07789491,0.02002347,16.89225,0.2707642,2.812156,-0.01600124,719.7424,9.512256,1.20064,100.2749,17.09632,84.50031,2.825158,16.78185,13.02122,0,0,0,0,0,50,-0.3134294,48.85725,0.01951842,0.1237964,0.7311883,4.901563,11.05024,16.5283,78.67393\r"
[7] "\"2016-06-09 09:30:00\",44803,-0.168336,60.68195,68.70016,64.93797,0.09754083,0.2851819,0.3828293,-0.06610256,-0.1205805,0.05701535,0.9924686,0.1423672,-0.020966,0.9882805,-0.07857981,0.3226543,2.501359,0.495024,0.7823009,-0.325776,0.1737764,-0.0131622,-0.04362109,0.02234407,17.18247,1.0204,2.391732,0.008349597,719.1043,9.466228,1.199341,100.2539,17.8618,66.89518,2.600309,21.11683,13.03483,0,0,0,0,0,50,-0.325776,54.51952,0.02178382,0.1356562,0.8121096,5.350313,10.98709,16.78893,77.00739\r"

In [58]:
data <- read.csv(
  "data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2016).dat",
  skip = 4, header = FALSE
)

In [59]:
headers <- read.csv(
  "data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2016).dat",
  skip = 1, header = FALSE, nrows = 3
)

In [60]:
headers

  V1        V2     V3         V4     V5    V6    V7         V8     V9
1 TIMESTAMP RECORD Fc_wpl     LE_wpl Hs    Hc    tau        u_star stdev_Ts
2 TS        RN     mg/(m^2 s) W/m^2  W/m^2 W/m^2 kg/(m s^2) m/s    C
3                  Smp        Smp    Smp   Smp   Smp        Smp    Smp
  V10       ⋯ V45      V46        V47     V48        V49        V50
1 cov_Ts_Ux ⋯ agc_Avg  Fc_irga    LE_irga co2_wpl_LE co2_wpl_H  h2o_wpl_LE
2 m C/s     ⋯ unitless mg/(m^2 s) W/m^2   mg/(m^2 s) mg/(m^2 s) W/m^2
3 Smp       ⋯ Avg      Smp        Smp     Smp        Smp        Smp
  V51       V52          V53        V54
1 h2o_wpl_H h2o_hmp_mean t_hmp_mean rh_hmp_mean
2 W/m^2     g/m^3        C          percent
3 Smp       Smp          Smp        Smp

In [61]:
write.table(
  headers, "data/CSV/TOA5_3989.2016.flux.headers.csv", row.names = FALSE,
  col.names = FALSE, sep = ",", quote = FALSE
)

In [62]:
names(data) <- as.matrix(
  read.csv(
    "data/TOA5/TOA5_3989.flux (2021_09_17 14_49_19 UTC) (2016).dat",
    skip = 1, header = FALSE, nrows = 1
  )
)

In [63]:
head(data)

  TIMESTAMP           RECORD Fc_wpl     LE_wpl   Hs        Hc        tau
1 2016-06-09 08:30:00 44801  -0.1307632 37.03913  25.60763  23.33440 0.11817510
2 2016-06-09 09:00:00 44802  -0.1701145 54.49001  62.58549  59.21500 0.10704210
3 2016-06-09 09:30:00 44803  -0.1683360 60.68195  68.70016  64.93797 0.09754083
4 2016-06-09 10:00:00 44804  -0.1584697 58.81278  63.49821  59.84708 0.11498450
5 2016-06-09 10:30:00 44805  -0.1508173 51.99655  66.14544  62.90998 0.11189950
6 2016-06-09 11:00:00 44806  -0.2001991 79.05721 114.46250 109.52880 0.15611540
  u_star    stdev_Ts  cov_Ts_Ux    ⋯ agc_Avg Fc_irga    LE_irga  co2_wpl_LE
1 0.3133757 0.2528313 -0.015055420 ⋯ 50      -0.1936334 34.59666 0.01385820
2 0.2985870 0.4525773  0.008037789 ⋯ 50      -0.3134294 48.85725 0.01951842
3 0.2851819 0.3828293 -0.066102560 ⋯ 50      -0.3257760 54.51952 0.02178382
4 0.3098198 0.3687277 -0.118348000 ⋯ 50      -0.3044280 53.02826 0.02116952
5 0.3056701 0.3978571 -0.078495500 ⋯ 50      -0.3005183 46.12586 0.01842926
6 0.3614822 0.5429151  0.020380990 ⋯ 50      -0.4554492 68.96523 0.02751203
  co2_wpl_H  h2o_wpl_LE h2o_wpl_H h2o_hmp_mean t_hmp_mean rh_hmp_mean
1 0.04901194 0.5003809  1.942085  10.70669     15.89368   79.20306
2 0.12379640 0.7311883  4.901563  11.05024     16.52830   78.67393
3 0.13565620 0.8121096  5.350313  10.98709     16.78893   77.00739
4 0.12478870 0.7973850  4.987134  11.07698     17.09130   76.24122
5 0.13127170 0.6915368  5.179154  11.04192     17.11374   75.89794
6 0.22773800 1.0457320  9.046240  11.13956     17.71659   73.86147

In [64]:
summary(data)

  TIMESTAMP             RECORD          Fc_wpl               LE_wpl
 Length:1355        Min.   :44801   Min.   :-6.065e+07   Min.   :-1136.733
 Class :character   1st Qu.:45140   1st Qu.: 0.000e+00   1st Qu.:    8.797
 Mode  :character   Median :45478   Median : 0.000e+00   Median :   37.100
                    Mean   :45478   Mean   : 3.569e+15   Mean   :   55.730
                    3rd Qu.:45816   3rd Qu.: 0.000e+00   3rd Qu.:   91.187
                    Max.   :46155   Max.   : 4.743e+18   Max.   : 2474.965
                                    NA's   :26           NA's   :26
       Hs                 Hc               tau               u_star
 Min.   :-360.390   Min.   :-346.11   Min.   :0.000574   Min.   :0.02169
 1st Qu.:  -9.702   1st Qu.: -10.41   1st Qu.:0.055775   1st Qu.:0.21442
 Median :   6.950   Median :   5.58   Median :0.116427   Median :0.31113
 Mean   :  30.313   Mean   :  26.96   Mean   :0.176259   Mean   :0.33535
 3rd Qu.:  55.308   3rd Qu.:  51.88   3rd Qu.:0.220417   3rd Qu.:0.42804
 Max.   :1056.908   Max.   : 996.10   Max.   :2.875404   Max.   :1.55185
 NA's   :26         NA's   :26        NA's   :26         NA's   :26
    stdev_Ts         cov_Ts_Ux           cov_Ts_Uy           cov_Ts_Uz
 Min.   :0.04541   Min.   :-0.856767   Min.   :-2.999002   Min.   :-0.301015
 1st Qu.:0.15900   1st Qu.:-0.069259   1st Qu.:-0.037226   1st Qu.:-0.007952
 Median :0.25631   Median :-0.004312   Median : 0.008747   Median : 0.005702
 Mean   :0.35012   Mean   : 0.003890   Mean   : 0.028823   Mean   : 0.025153
 3rd Qu.:0.47141   3rd Qu.: 0.051658   3rd Qu.: 0.088742   3rd Qu.: 0.046041
 Max.   :1.49380   Max.   : 1.947644   Max.   : 0.733082   Max.   : 0.882629
 NA's   :26        NA's   :26          NA's   :26          NA's   :26
    stdev_Ux        cov_Ux_Uy          cov_Ux_Uz            stdev_Uy
 Min.   :0.1198   Min.   :-4.62317   Min.   :-1.794579   Min.   :0.1294
 1st Qu.:0.8114   1st Qu.:-0.18949   1st Qu.:-0.104846   1st Qu.:0.7584
 Median :1.0722   Median :-0.04193   Median :-0.042156   Median :0.9917
 Mean   :1.1008   Mean   :-0.09940   Mean   :-0.064115   Mean   :1.0250
 3rd Qu.:1.3436   3rd Qu.: 0.05084   3rd Qu.:-0.000559   3rd Qu.:1.2507
 Max.   :3.1105   Max.   : 0.86248   Max.   : 1.206643   Max.   :2.8133
 NA's   :26       NA's   :26         NA's   :26          NA's   :26
   cov_Uy_Uz            stdev_Uz        stdev_co2           cov_co2_Ux
 Min.   :-2.084143   Min.   :0.0337   Min.   :0.000e+00   Min.   :-1.383e+07
 1st Qu.:-0.006597   1st Qu.:0.2964   1st Qu.:2.000e+00   1st Qu.:-1.000e+00
 Median : 0.016971   Median :0.3933   Median :4.000e+00   Median : 0.000e+00
 Mean   : 0.026376   Mean   :0.4092   Mean   :2.523e+06   Mean   : 1.529e+17
 3rd Qu.: 0.071739   3rd Qu.:0.5132   3rd Qu.:4.600e+01   3rd Qu.: 1.000e+00
 Max.   : 0.716898   Max.   :1.0157   Max.   :3.415e+09   Max.   : 2.032e+20
 NA's   :26          NA's   :26       NA's   :1           NA's   :26
   cov_co2_Uy           cov_co2_Uz           stdev_h2o         cov_h2o_Ux
 Min.   :-3.045e+20   Min.   :-6.066e+07   Min.   : 0.0306   Min.   :-2.87652
 1st Qu.:-2.000e+00   1st Qu.: 0.000e+00   1st Qu.: 0.1762   1st Qu.:-0.08585
 Median : 0.000e+00   Median : 0.000e+00   Median : 0.3584   Median :-0.01288
 Mean   :-2.291e+17   Mean   : 3.578e+15   Mean   : 1.1551   Mean   : 0.01119
 3rd Qu.: 0.000e+00   3rd Qu.: 0.000e+00   3rd Qu.: 1.9349   3rd Qu.: 0.04730
 Max.   : 4.511e+06   Max.   : 4.755e+18   Max.   :33.9872   Max.   : 3.10678
 NA's   :26           NA's   :26                             NA's   :26
   cov_h2o_Uy         cov_h2o_Uz           Ts_mean           Ux_Avg
 Min.   :-4.37407   Min.   :-0.450333   Min.   : 8.293   Min.   :-4.8816
 1st Qu.:-0.01725   1st Qu.: 0.003714   1st Qu.:13.364   1st Qu.: 0.3015
 Median : 0.03116   Median : 0.014659   Median :14.398   Median : 2.5169
 Mean   : 0.06055   Mean   : 0.021697   Mean   :14.507   Mean   : 2.2418
 3rd Qu.: 0.13624   3rd Qu.: 0.035165   3rd Qu.:15.615   3rd Qu.: 4.1078
 Max.   : 2.19879   Max.   : 0.996682   Max.   :19.818   Max.   :11.1110
 NA's   :26         NA's   :26          NA's   :26       NA's   :26
     Uy_Avg            Uz_Avg            co2_mean            h2o_Avg
 Min.   :-7.0233   Min.   :-0.67717   Min.   :4.740e+02   Min.   :-9.434
 1st Qu.:-3.3430   1st Qu.: 0.05444   1st Qu.:7.150e+02   1st Qu.: 4.867
 Median :-1.5274   Median : 0.11581   Median :7.280e+02   Median : 7.373
 Mean   :-1.7391   Mean   : 0.11069   Mean   :5.530e+16   Mean   : 6.107
 3rd Qu.:-0.3186   3rd Qu.: 0.16796   3rd Qu.:7.480e+02   3rd Qu.: 8.352
 Max.   : 3.8606   Max.   : 0.38665   Max.   :7.494e+19   Max.   :12.718
 NA's   :26        NA's   :26
   rho_a_mean      press_mean     panel_temp_Avg      wind_dir
 Min.   :1.179   Min.   : 98.02   Min.   : 6.821   Min.   :-168.739
 1st Qu.:1.197   1st Qu.: 99.18   1st Qu.:13.107   1st Qu.: -66.218
 Median :1.205   Median : 99.78   Median :14.408   Median : -25.689
 Mean   :1.205   Mean   : 99.68   Mean   :14.640   Mean   : -33.557
 3rd Qu.:1.213   3rd Qu.:100.22   3rd Qu.:16.176   3rd Qu.:  -4.716
 Max.   :1.241   Max.   :100.71   Max.   :21.551   Max.   : 176.214

  rslt_wnd_spd       std_wnd_dir    batt_volt_Avg   irga_warnings
 Min.   : 0.09772   Min.   : 0.00   Min.   :12.84   Min.   :0.000000
 1st Qu.: 2.79055   1st Qu.:11.11   1st Qu.:12.98   1st Qu.:0.000000
 Median : 3.95551   Median :13.29   Median :13.00   Median :0.000000
 Mean   : 4.11119   Mean   :16.05   Mean   :12.99   Mean   :0.008856
 3rd Qu.: 5.30081   3rd Qu.:16.67   3rd Qu.:13.02   3rd Qu.:0.000000
 Max.   :11.14893   Max.   :75.04   Max.   :13.07   Max.   :3.000000
 NA's   :26
 chopper_f_Tot detector_f_Tot   pll_f_Tot   sync_f_Tot    agc_Avg
 Min.   :0     Min.   :0      Min.   :0   Min.   :0    Min.   :50.00
 1st Qu.:0     1st Qu.:0      1st Qu.:0   1st Qu.:0    1st Qu.:50.00
 Median :0     Median :0      Median :0   Median :0    Median :50.00
 Mean   :0     Mean   :0      Mean   :0   Mean   :0    Mean   :57.25
 3rd Qu.:0     3rd Qu.:0      3rd Qu.:0   3rd Qu.:0    3rd Qu.:60.63
 Max.   :0     Max.   :0      Max.   :0   Max.   :0    Max.   :94.00

    Fc_irga              LE_irga            co2_wpl_LE
 Min.   :-6.066e+07   Min.   :-1098.812   Min.   :-1.136e+16
 1st Qu.: 0.000e+00   1st Qu.:    9.063   1st Qu.: 0.000e+00
 Median : 0.000e+00   Median :   35.767   Median : 0.000e+00
 Mean   : 3.578e+15   Mean   :   52.941   Mean   :-8.549e+12
 3rd Qu.: 0.000e+00   3rd Qu.:   85.802   3rd Qu.: 0.000e+00
 Max.   : 4.755e+18   Max.   : 2431.905   Max.   : 2.464e+04
 NA's   :26           NA's   :26          NA's   :26
   co2_wpl_H            h2o_wpl_LE         h2o_wpl_H         h2o_hmp_mean
 Min.   :-4.583e+14   Min.   :-17.5325   Min.   :-33.9699   Min.   : 6.921
 1st Qu.: 0.000e+00   1st Qu.:  0.1198   1st Qu.: -0.6636   1st Qu.: 9.068
 Median : 0.000e+00   Median :  0.4693   Median :  0.4957   Median : 9.816
 Mean   :-3.448e+11   Mean   :  0.7144   Mean   :  2.0743   Mean   : 9.913
 3rd Qu.: 0.000e+00   3rd Qu.:  1.1191   3rd Qu.:  3.9635   3rd Qu.:10.765
 Max.   : 2.000e+00   Max.   : 37.5714   Max.   : 85.0185   Max.   :13.195
 NA's   :26           NA's   :26         NA's   :26
   t_hmp_mean      rh_hmp_mean
 Min.   : 7.412   Min.   :53.37
 1st Qu.:12.795   1st Qu.:76.38
 Median :13.738   Median :84.58
 Mean   :13.848   Mean   :83.02
 3rd Qu.:14.930   3rd Qu.:90.49
 Max.   :18.628   Max.   :96.84

In [65]:
nrow(data)

[1] 1355

In [66]:
write.table(
  headers, "data/CSV/TOA5_3989.2016.flux.csv", row.names = FALSE,
  sep = ",", quote = FALSE
)